### ISSUE TITLE
Script Lab error

### ISSUE THREAD

**Issue by AndyH420** [OfficeDev/script-lab#1007]
Hello,

I'm unable to load Script Lab properly since some code edits (possibly something I edited in the libraries section) and I get the following error:

Error:
{
    "stack": "TypeError: Failed to fetch\n    at https://script-lab.azureedge.net/static/js/main.2d036e31.chunk.js:2:232000\n    at l (https://script-lab.azureedge.net/static/js/main.2d036e31.chunk.js:2:224382)\n    at Generator.<anonymous> (https://script-lab.azureedge.net/static/js/main.2d036e31.chunk.js:2:225723)\n    at Generator.next (https://script-lab.azureedge.net/static/js/main.2d036e31.chunk.js:2:224745)\n    at r (https://script-lab.azureedge.net/static/js/3.3abf3183.chunk.js:2:138783)\n    at s (https://script-lab.azureedge.net/static/js/3.3abf3183.chunk.js:2:138986)\n    at https://script-lab.azureedge.net/static/js/3.3abf3183.chunk.js:2:139045\n    at new Promise (<anonymous>)\n    at https://script-lab.azureedge.net/static/js/3.3abf3183.chunk.js:2:138926\n    at es (https://script-lab.azureedge.net/static/js/main.2d036e31.chunk.js:2:231758)",
    "message": "Failed to fetch",
    "sagaStack": "at ff \n at ff \n at l \n at js \n at Ls \n TypeError: Failed to fetch\n    at https://script-lab.azureedge.net/static/js/main.2d036e31.chunk.js:2:232000\n    at l (https://script-lab.azureedge.net/static/js/main.2d036e31.chunk.js:2:224382)\n    at Generator.<anonymous> (https://script-lab.azureedge.net/static/js/main.2d036e31.chunk.js:2:225723)\n    at Generator.next (https://script-lab.azureedge.net/static/js/main.2d036e31.chunk.js:2:224745)\n    at r (https://script-lab.azureedge.net/static/js/3.3abf3183.chunk.js:2:138783)\n    at s (https://script-lab.azureedge.net/static/js/3.3abf3183.chunk.js:2:138986)\n    at https://script-lab.azureedge.net/static/js/3.3abf3183.chunk.js:2:139045\n    at new Promise (<anonymous>)\n    at https://script-lab.azureedge.net/static/js/3.3abf3183.chunk.js:2:138926\n    at es (https://script-lab.azureedge.net/static/js/main.2d036e31.chunk.js:2:231758)"
}

Any help would be much appreciated.

Regards
Andy

**Comment by wandyezj** [comment]
If you are ok losing all local scripts, you can do an empty cache hard refresh with script lab open.

You can also use F12 tools to view Script Labs scripts in localStorage, you can then download your script and delete it to load Script Lab.

Generally, I would not recommend adding libraries to Script Lab.

If your script is getting too big, or if you need to use libraries, I recommend creating an full [Add-In](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/develop-overview)

You can create and host your own Add-In on GitHub, for example see the [Build Add-In](https://github.com/wandyezj/website-react-extension) you can sideload the [manifest](https://github.com/wandyezj/website-react-extension/blob/main/manifests/production.xml)
