### ISSUE TITLE
An unexpected error has occurred.

### ISSUE THREAD

**Issue by AndyH420** [OfficeDev/script-lab#1008]
Hi,

I keep getting the following error whenever I use Script Lab. Any ideas?

Error:
{
    "stack": "TypeError: Failed to fetch\n    at https://script-lab.azureedge.net/static/js/main.2d036e31.chunk.js:2:232000\n    at l (https://script-lab.azureedge.net/static/js/main.2d036e31.chunk.js:2:224382)\n    at Generator.<anonymous> (https://script-lab.azureedge.net/static/js/main.2d036e31.chunk.js:2:225723)\n    at Generator.next (https://script-lab.azureedge.net/static/js/main.2d036e31.chunk.js:2:224745)\n    at r (https://script-lab.azureedge.net/static/js/3.3abf3183.chunk.js:2:138783)\n    at s (https://script-lab.azureedge.net/static/js/3.3abf3183.chunk.js:2:138986)\n    at https://script-lab.azureedge.net/static/js/3.3abf3183.chunk.js:2:139045\n    at new Promise (<anonymous>)\n    at https://script-lab.azureedge.net/static/js/3.3abf3183.chunk.js:2:138926\n    at es (https://script-lab.azureedge.net/static/js/main.2d036e31.chunk.js:2:231758)",
    "message": "Failed to fetch",
    "sagaStack": "at ff \n at ff \n at l \n at js \n at Ls \n TypeError: Failed to fetch\n    at https://script-lab.azureedge.net/static/js/main.2d036e31.chunk.js:2:232000\n    at l (https://script-lab.azureedge.net/static/js/main.2d036e31.chunk.js:2:224382)\n    at Generator.<anonymous> (https://script-lab.azureedge.net/static/js/main.2d036e31.chunk.js:2:225723)\n    at Generator.next (https://script-lab.azureedge.net/static/js/main.2d036e31.chunk.js:2:224745)\n    at r (https://script-lab.azureedge.net/static/js/3.3abf3183.chunk.js:2:138783)\n    at s (https://script-lab.azureedge.net/static/js/3.3abf3183.chunk.js:2:138986)\n    at https://script-lab.azureedge.net/static/js/3.3abf3183.chunk.js:2:139045\n    at new Promise (<anonymous>)\n    at https://script-lab.azureedge.net/static/js/3.3abf3183.chunk.js:2:138926\n    at es (https://script-lab.azureedge.net/static/js/main.2d036e31.chunk.js:2:231758)"
}

Regards
Andy

**Comment by wandyezj** [comment]
I'm not sure. Were you able to get it working with the latest version?
