### ISSUE TITLE
Cannot run custom functions

### ISSUE THREAD

**Issue by jemery27** [OfficeDev/script-lab#1014]
Excel custom functions in Windows 11 - even loading the basic example named "Basic Custom Function" that calculates the volume of a sphere - when you click register it reports error:

ADD-IN ERROR
This add-in could not be started. Close this dialog box to ignore the problem or click "Restart" to try again.

Clicking Restart just resets and returns the same error.

I have tried removing and reinstalling Script Lab and checked Trust Center Add-in settings.

This error occurs on other custom functions as well.

Thank you,
Jason

![image](https://github.com/OfficeDev/script-lab/assets/14082992/dfa52164-487a-4aa9-8a52-78a25a08acd5)

### Bug Report

- **Host**: (fill out if relevant. eg: EXCEL, WORD)
- **OS**: (fill out if relevant/applicable)
- **Browser**: (fill out if relevant/applicable)
- **Environment**: (fill out. eg: alpha, beta, prod)

#### Steps to Reproduce:

1. step 1
2. step 2
3. etc...

**Comment by chrisloveit** [comment]
Hi there,

I am encountering the exact same issue with Excel and Script Lab.

I'm using the following version of Excel: Microsoft® Excel® for Microsoft 365 MSO (Version 2307 Build 16.0.16626.20170) 64-bit.

Best regards,
Christophe

**Comment by akrantz** [comment]
A fix was recently made which should address this. Please try it now, and let us know if you're still having problems.

**Comment by jemery27** [comment]
I'm not sure if there is something else I would have to do to fix this, but going into blank excel workbook, click script lab tab, then code, then select the basic custom function and click register. At first it does register the function and then in the workbook I can use it in a formula, but as soon as I hit enter I get the same error as before. If I try re-registering the function I get the same error. If I click the restart button shown in the error it just flashes and shows the same error.

I also tried removing scriptlab and re-adding it - not sure if it needs some kind of update.

My OS is Windows 11. Is there any other info I could provide?
