### ISSUE TITLE
Office for Web: limited to port 3000

### ISSUE THREAD

**Issue by justmars** [OfficeDev/script-lab#1016]
### Bug Report

- **Host**: Word / Office for Web
- **OS**: Mac
- **Browser**: Edge
- **Environment**: prod

#### Expected behavior:

While running a server on https://localhost:8000, I should be able to use 

```js
$("#run").click(() => tryCatch(run));

async function run() {
  Office.context.ui.displayDialogAsync(
        "https://localhost:8000/test",
        { height: 50, width: 30 },
        function (asyncResult) {
          console.log(JSON.stringify(asyncResult));
          if (asyncResult.status === Office.AsyncResultStatus.Failed) {
            console.log(
              (asyncResult.error.code = ": " + asyncResult.error.message)
            );
          } else {
            console.log("Display dialog separate window")
          }
        }
      )
    }


/** Default helper for invoking an action and handling errors. */
async function tryCatch(callback) {
  try {
    await callback();
  } catch (error) {
    // Note: In a production add-in, you'd want to notify the user through your add-in's UI.
    console.error(error);
  }
}
```

#### Actual behavior:

I get the following result:

```console
{"status":"failed","error":{"name":"Display Dialog Error","message":"The domain of the URL is not included in the AppDomains element in the manifest, and is not subdomain of source location.","code":12004}}
: The domain of the URL is not included in the AppDomains element in the manifest, and is not subdomain of source location.
```

#### Steps to Reproduce:

1. Run server at localhost:8000
2. Run office on the web with MS Word
3. Install script lab
4. Add code describe above to script lab 
5. Run script lab inputted code

See discussion here https://github.com/OfficeDev/office-js/issues/3586#issuecomment-1683297315

Am I correct that localhost / dialog links will always need to be port 3000 in script lab? When switching the server to 3000, everything seems to work as documented.

**Comment by akrantz** [comment]
You're correct that only localhost:3000 is listed in the AppDomains for the ScriptLab add-in. Other port numbers won't work.

**Comment by wandyezj** [comment]
We no longer allow localhost in the appdomains.

If you need to use this advanced feature, I recommend creating a full [Add-In](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/develop-overview)

You can create and host your own Add-In on GitHub, for example see the [Build Add-In](https://github.com/wandyezj/website-react-extension) you can sideload the [manifest](https://github.com/wandyezj/website-react-extension/blob/main/manifests/production.xml) to try it out.
