### ISSUE TITLE
Need designers if we want dark theme everywhere

### ISSUE THREAD

**Issue by nico-bellante** [OfficeDev/script-lab#102]
I tried to naively play with the theme and settings last night to make the dark theme apply everywhere. The results were less that satisfactory...

![image](https://user-images.githubusercontent.com/35939126/45317656-7bae3d00-b4ef-11e8-8436-07da4e0b6f1c.png)
![image](https://user-images.githubusercontent.com/35939126/45317679-8963c280-b4ef-11e8-8310-979873a1e164.png)

**Comment by wandyezj** [comment]
Obsolete. Script Lab should move to use Fluent 2.
