### ISSUE TITLE
Full-text search for samples

### ISSUE THREAD

**Issue by nico-bellante** [OfficeDev/script-lab#103]
In order to properly search through samples efficiently, we will need to have our server have a search endpoint that takes a query string, and returns back all the samples that match this string. This is because the alternative includes getting the full contents of every single sample on load just to search through them. These samples can be rather large, and would take up a lot of the user's network bandwidth.

**Comment by Zlatkovsky** [comment]
For the simple search (by just name + description), it's already being done in #569

**Comment by wandyezj** [comment]
Obsolete.
