### ISSUE TITLE
import other scripts

### ISSUE THREAD

**Issue by tejo-ak** [OfficeDev/script-lab#1035]
We need to get organize with our script and it is getting unmanageable when our script getting bigger where we need a lot of scrolls, beside the script become unmanageable. 

Therefore, I propose the Script lab to be able import other scripts. It will enable us to break a long script into several - modular scripts. 

Thanks for considering.

**Comment by wandyezj** [comment]
This seems like cool feature. However, the purpose of Script Lab is to allow people to trial things out. 

If your script is getting too big I recommend creating an full [Add-In](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/develop-overview)

You can create and host your own Add-In on GitHub, for example see the [Build Add-In](https://github.com/wandyezj/website-react-extension) you can sideload the [manifest](https://github.com/wandyezj/website-react-extension/blob/main/manifests/production.xml)
