### ISSUE TITLE
Uncaught Type Error - Outlook Web

### ISSUE THREAD

**Issue by muhbalhester** [OfficeDev/script-lab#1043]
### Bug Report

- **Host**: Outlook Web
- **OS**: (fill out if relevant/applicable)
- **Browser**: Edge
- **Environment**: (fill out. eg: alpha, beta, prod)

#### Expected behavior:

The script should execute as expected when the user interact with the script.

#### Actual behavior:

When a function is executed the Office script returns an error.

#### Steps to Reproduce:

1. Choose an snippet to run (can be one of the exmples snippet)
2. Run it
3. Interact with the snippet ui generated (click a button to execute a function)

#### Failure Logs:

An unexpected error has occurred.
Uncaught TypeError: Right-hand side of 'instanceof' is not an object

#### Screenshot:

![image](https://github.com/OfficeDev/script-lab/assets/22015418/0be2cdec-a888-4b93-a8cd-878be85211e3)

**Comment by wandyezj** [comment]
This should be fixed as of 2024-04-05. Browser caches might take a little bit to clear.
