### ISSUE TITLE
heal

### ISSUE THREAD

**Issue by Z1C8A18Y** [OfficeDev/script-lab#1050]
![24px-Symbol_redirect_vote2 svg](https://github.com/OfficeDev/script-lab/assets/165836116/30bba89a-4b87-4d76-b4bd-e39b0a41f333)

### Bug Report

- **Host**: (fill out if relevant. eg: EXCEL, WORD)
- **OS**: (fill out if relevant/applicable)
- **Browser**: (fill out if relevant/applicable)
- **Environment**: (fill out. eg: alpha, beta, prod)

#### Steps to Reproduce:

1. step 1
2. step 2
3. etc...

**Comment by wandyezj** [comment]
Could you please provide more information?
