### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by marcusbai** [OfficeDev/script-lab#1055]
# Bug Report

## Environment

- **Host**: word 
- **OS**: Windows 11

## Failure Logs
add-on Error 
Failed to start this add-on. Please close this dialog box to ignore this issue, or click "Restart" to try again.

Access Denied
You don't have permission to access "http://script-lab.public.cdn.office.net/script-lab/7dttl/run.html?" on this server.
Reference #18.6c10e47a.1715061275.3d9659

https://errors.edgesuite.net/18.6c10e47a.1715061275.3d9659

## Screenshot

<img width="236" alt="Snipaste_2024-05-07_14-38-56" src="https://github.com/OfficeDev/script-lab/assets/16847894/54604a31-07a9-47e3-ad5f-590880868622">

**Comment by wandyezj** [comment]
Hello @marcusbai 

Are you running Script Lab behind a firewall? If so, you will need to add this domain to the allow list.

Generally, all `*.public.cnd.office.net` domains should be on the allow list.

**Comment by marcusbai** [comment]
> Hello @marcusbai
> 
> Are you running Script Lab behind a firewall? If so, you will need to add this domain to the allow list.
> 
> Generally, all `*.public.cnd.office.net` domains should be on the allow list.

Thank you very much. I've tried a few methods, but they don't work. 
Also, is this issue related to usage within mainland China?

**Comment by wandyezj** [comment]
> is this issue related to usage within mainland China?

Sometimes networks block domains. Have you tried using a VPN?

**Comment by marcusbai** [comment]
> Sometimes networks block domains. Have you tried using a VPN?

Thanks a lot. I've tried it, but it's still not working. I'm not sure if anyone else is experiencing this issue. It's very strange indeed. :sob:
