### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by ruhchjdbdbhccjjc** [OfficeDev/script-lab#1064]
# Bug Report

## Environment
Host:Excel(web and Desktop)
OS: Windows 11

## Expected behavior
  Thank for your work ! 
  Before a while,it can load successful without any error ,
    but recent ,always load  failed .
    I haved try all suggestion  in this same error (> Access Denied #1055),but do not work .
   I am now  in china .Is this be a reason ？
   
 would you give some other suggestion ?
 Have a nice day!

## Actual behavior
Sucessful load!

## Failure Logs
add-on Error
Failed to start this add-on. Please close this dialog box to ignore this issue, or click "Restart" to try again.

Access Denied
You don't have permission to access "http://script-lab.public.cdn.office.net/script-lab/7dttl/run.html?" on this server.
Reference https://github.com/OfficeDev/script-lab/issues/18.6c10e47a.1715061275.3d9659

https://errors.edgesuite.net/18.6c10e47a.1715061275.3d9659

## Screenshot
tring to run in local (follow https://github.com/OfficeDev/script-lab/issues/999#issuecomment-2038075394), but  always  on load 
![image](https://github.com/OfficeDev/script-lab/assets/76729215/2098b621-208f-4f55-b4a1-e163a3d27942)
install from add-in store always error .just same as Access Denied #1055

![image](https://github.com/OfficeDev/script-lab/assets/76729215/bf08d47f-4250-4a9b-bbe3-1c7901d80fee)

**Comment by wandyezj** [comment]
Sometimes networks block domains. Have you tried using a VPN?

**Comment by ruhchjdbdbhccjjc** [comment]
Thanks for advice , Follow your suggest , I haved sucessful load script-lab by trying add 
 several  domains rules  to   networks.
Have a nice day !
