### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by L-LingXiao-X** [OfficeDev/script-lab#1068]
# Bug Report

I am encountering an "Access Denied" error when attempting to access Microsoft Script Lab add-in.

## Environment

- **Host**:All Microsoft 365 Apps
- **OS**: Windows11
- **Browser**: Microsoft Edge

## Expected behavior

The add-in should start normally.

## Actual behavior

Upon installation and launch of the add-in, an "Access Denied" message is displayed in the window.

## Steps to Reproduce

1.Install the Microsoft Script Lab add-in.
2.Attempt to run the add-in.
3.Observe the "Access Denied" error.

## Failure message
```
Access Denied
You don't have permission to access "http://script-lab.public.cdn.office.net/script-lab/7dttl/run.html?" on this server.
Reference #18.35e53774.1720763364.41d306e
https://errors.edgesuite.net/18.35e53774.1720763364.41d306e
```
## Screenshot
![image](https://github.com/user-attachments/assets/e33ee05f-0f92-4e3d-8703-91455c86457a)  
## Additional Information
*** This content is machine translated. ***
I apologize if this is a network-related issue. Thank you for your assistance in resolving this matter.

**Comment by 0x1orz** [comment]
Script Lab  could be loaded from China location with a network proxy.
![1](https://github.com/user-attachments/assets/7f8cd692-d0e4-4136-9e0f-97a4ecc381aa)

**Comment by kenwdcao** [comment]
Same issue. Why so many Microsoft service don't work when VPN is connected???

**Comment by WidexGH** [comment]
Just clear the office cache by following the steps in https://learn.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache

You may have to close the office applications before doing so. Once it is done, you will have to reload the script, and it will work fine.
