### ISSUE TITLE
Investigate registerServiceWorker

### ISSUE THREAD

**Issue by nico-bellante** [OfficeDev/script-lab#116]
It was removed for the editor in #115, but should probably be brought back at some point in the future if we can work through the caching issue.

**Comment by Zlatkovsky** [comment]
@nico-bellante , care to describe what this is for?  Or if not, should we just close it?...

**Comment by Zlatkovsky** [comment]
@nico-bellante , ping.

**Comment by wandyezj** [comment]
Obsolete. We do not need a service worker.
