### ISSUE TITLE
Playground stops rendering after Reload

### ISSUE THREAD

**Issue by jakobpn** [OfficeDev/script-lab#130]
![image](https://cloud.githubusercontent.com/assets/13109307/22519411/01d45d64-e865-11e6-8f2e-fcb48d82eac5.png)

On Windows

**Comment by Zlatkovsky** [comment]
This looks very old.  I'm assuming the issue has resolved itself, or else this would have been a ship-blocker?

**Comment by jakobpn** [comment]
Yes, I don't think it repros anymore.
