### ISSUE TITLE
Pasting .yaml from the playground to Github doesn't work for Uma/Juan

### ISSUE THREAD

**Issue by jakobpn** [OfficeDev/script-lab#206]
https://github.com/umasubra/samples/blob/3813a8dd86345110ef9a4c717b4d6f73d4165a86/samples/excel/tables/format-table.yaml

See script part of this sample

This should be multiple lines. Not a single line.

![image](https://cloud.githubusercontent.com/assets/13109307/23975621/169a3f88-099f-11e7-8574-90f12a828d8e.png)

**Comment by Zlatkovsky** [comment]
Duplicate of https://github.com/OfficeDev/script-lab/issues/206.
Closing this one.
