### ISSUE TITLE
Collapse samples by default

### ISSUE THREAD

**Issue by Zlatkovsky** [OfficeDev/script-lab#234]
### Description:

Recording old feedback:  Should we collapse sample groups by default?  And/or once we have search for samples, does it not even matter?

https://github.com/OfficeDev/script-lab-react/issues/103

**Comment by Zlatkovsky** [comment]
@AlexJerabek , assigning this to you as representative of the Docs team.
We will (soon) have the ability for samples to be searched by title & description.  (PR #569 ).  In which case I don't know if we need this.
But if you think collapsing everything by default would be good, it's an easy fix.

**Comment by Zlatkovsky** [comment]
And if you don't think this issue (the feature request for collapsing) is needed anymore, please go ahead and just close the issue.

**Comment by AlexJerabek** [comment]
I'll poll the docs team and read their opinions on the subject. Searching is definitely awesome and welcome.

**Comment by Zlatkovsky** [comment]
Now that we have search, closing this one.
