### ISSUE TITLE
Can't sign in in IE11:  Not authorizing access to GitHub profile

### ISSUE THREAD

**Issue by AlexJerabek** [OfficeDev/script-lab#248]
### Bug Report

- **Host**: EXCEL
- **OS**: Windows 10
- **Browser**: N/A
- **Environment**: beta

#### Expected behavior:

After signing in to GitHub and authorizing Script Lab to access my GitHub profile, I expect to be able to progress through the windows.

#### Actual behavior:

The authorize button is unclickable (as seen in the included screenshot). I'm unsure if the procedure finished, but the GitHub profile button in Script Lab is blank and does nothing when clicked.

#### Steps to Reproduce:

1. Click on the GitHub icon in the upper-right corner when not logged in.
2. Log in to a profile that has not been authorized yet.

#### Screenshot:

![scriptlabauth](https://user-images.githubusercontent.com/38896772/47185976-e8cda300-d2e3-11e8-8c2e-9e7fea5377ec.png)

**Comment by Zlatkovsky** [comment]
Merging in this issue with https://github.com/OfficeDev/script-lab-2017/issues/887 (closing the latter as a duplicate).

For someone new coming to this thread:  In the meantime, one workaround is for you to go to https://script-lab.azureedge.net/?host=EXCEL from a non-IE browser and click "sign in" there. Once you've signed in, close the browser, and try signing in from within Office again. It should bypass this page and succeed.

We'll keep the issue open to track the final resolution, which I'll be working on starting soon.
