### ISSUE TITLE
Telemetry

### ISSUE THREAD

**Issue by nico-bellante** [OfficeDev/script-lab#27]
Hook up basic initial telemetry

**Comment by Zlatkovsky** [comment]
Waiting till Geoffrey checks in a fix to make it easier for us to consume otel.js

**Comment by Zlatkovsky** [comment]
Note:  will also need to complete https://office.visualstudio.com/DefaultCollection/OC/OEP/_workitems/edit/2694295 before we're done.

**Comment by Zlatkovsky** [comment]
This is no longer blocked.  Just needs the ~2 days of work (plus making sure we do the privacy assessment, etc.).
Shelved work is on my desktop computer, and I added notes to our OneNote for what we need to restart this work.
