### ISSUE TITLE
Should prompt if importing an external gist that's already been imported before

### ISSUE THREAD

**Issue by nico-bellante** [OfficeDev/script-lab#274]
### Description:
Right now, if you import a gist via the import field three times, this will appear as 3 separate gists locally. This should go through the same pipeline as the opening your own gist goes through where it checks to see if it exists locally first.

Additionally, if a user imports their own gist while not signed in, then signs in, they should be able to update that gist.

**Comment by wandyezj** [comment]
Obsolete.

It's easier to have a clear boundary between internal and external.

We will always make a copy for a new import.
