### ISSUE TITLE
Bug: Focusing the monaco editor on iPhone zooms in super far

### ISSUE THREAD

**Issue by nico-bellante** [OfficeDev/script-lab#275]
### Bug Report

- **OS**: iOS
- **Browser**:  safari
- **Environment**: alpha

When focusing the Monaco editor, it zooms in ridiculously far.

**Comment by Zlatkovsky** [comment]
Since this scenario isn't supported for now, closing it.  We'll need to test holistically if we decide to support iOS/iPhone
