### ISSUE TITLE
Spilling buttons in the header

### ISSUE THREAD

**Issue by Zlatkovsky** [OfficeDev/script-lab#318]
Alpha

![image](https://user-images.githubusercontent.com/2230453/48734438-42363400-ebfa-11e8-856e-71016371122b.png)

**Comment by Zlatkovsky** [comment]
Removing "stale" tag.  There are definitely still issues with the header layout, such as:

![image](https://user-images.githubusercontent.com/2230453/50568054-80e30200-0d01-11e9-88b9-592ccdd07730.png)

Or the label disappearing altogether, leaving just "..." and giant white-space, where I now need to click on the "...":

![image](https://user-images.githubusercontent.com/2230453/50568045-70cb2280-0d01-11e9-83ed-69a01effb59c.png)

**Comment by wandyezj** [comment]
Obsolete. Fix by moving to Fluent 2
