### ISSUE TITLE
Save locally experience is tricky

### ISSUE THREAD

**Issue by gergzk** [OfficeDev/script-lab#326]
### Bug Report

- **Host**: Excel Win32
- **OS**: Win10
- **Browser**: (fill out if relevant/applicable)
- **Environment**: SLR-Beta

#### Expected behavior:

Not sure, exactly

#### Actual behavior:

To save a snippet locally and not have it get overwritten, I have to realize to click its name and rename it. This is hard to discover.

#### Steps to Reproduce:

Create a new sample snippet. Edit it. Create a new one. The previous one is gone.

**Comment by Zlatkovsky** [comment]
Gergely, Lena:  do you have a concrete proposal for what should be done here?  Beyond adding a tooltip (tracked separately by #324)?  If not, I think we should either close it, or move it off to some "Needs fresh ideas" milestone so that it's not clogging up more pressing actionable issues.

**Comment by gergzk** [comment]
So I guess the existing doesn't get overwritten, but rather a new one is created with a different name (eg: "Blank Snippet (2)"). As a user, I may not have ever registered that there's a name ... but this seems like a thing you just learn over time. I'm just going to close this.
