### ISSUE TITLE
Silent fail when publishing snippet "ScriptLab Bug Bush 22@_11,.//"

### ISSUE THREAD

**Issue by evanargelion** [OfficeDev/script-lab#327]
### Bug Report

- **Host**: Excel
- **OS**: Windows 10 64bit
- **Browser**: Chrome
- **Environment**: React beta

#### Expected behavior:

Publish to gist failed and scriptlab shows an error message.

#### Actual behavior:

Silent fail when publishing snippet with name "ScriptLab Bug Bush 22@_11,.//" with "No Custom UI" checked

#### Steps to Reproduce:

1. Create a snippet, rename it to "ScriptLab Bug Bush 22@_11,.//"
2. Try to publish to gist, either public or secret
3. Silent failed
#### Failure Logs:
Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)

**Comment by wandyezj** [comment]
Obsolete. GitHub integration is no longer supported.
