### ISSUE TITLE
Message bar "view link" text is cut off (and could disappear altogether in smaller screen size)

### ISSUE THREAD

**Issue by tiecmdr** [OfficeDev/script-lab#328]
alpha

![image](https://user-images.githubusercontent.com/11412640/48739044-9eec1b80-ec07-11e8-9e7a-4df5056d5d16.png)

**Comment by Zlatkovsky** [comment]
Not sure how relevant this still is.  Feel free to close if it's not.  Moving out slightly in any case, since haven't seen any real examples of it recently.

**Comment by Zlatkovsky** [comment]
Haven't seen any recent examples of this happening.  Closing.
