### ISSUE TITLE
Neither F2 nor ctrl+space work in Word (nor in today's Script Lab);  Neither does ctrl+f

### ISSUE THREAD

**Issue by Zlatkovsky** [OfficeDev/script-lab#331]
Might be more of a platform bug.  (And is same as what Script Lab has today).

Questions for us in the meantime:  should we find a different F key that *does* work, and do it for Word only?

**Comment by Zlatkovsky** [comment]
@peronald , assigning to you to re-route to the platform (and also to figure out if there is anything we want to do in the short term about this...).
The swallowing of keyboard shortcuts, esp. for something as common as "ctrl+f", seems like a real problem.

**Comment by wandyezj** [comment]
- `ctrl + f` works today.
- `F2` has been questionably overwritten.

We should probably allow F2 to do it's default behavior.

**Comment by wandyezj** [comment]
Fixed.
