### ISSUE TITLE
Gists are not displayed after sign in

### ISSUE THREAD

**Issue by jakobpn** [OfficeDev/script-lab#335]
Repro:
1. Open Script Lab from Store
2. Sign in to Github

Expected: Gists would be shown.
Actual: The "no gists" message below is shown.

![image](https://cloud.githubusercontent.com/assets/13109307/25067271/01a8443c-21f3-11e7-8f6a-5374bbb50b88.png)

**Comment by WrathOfZombies** [comment]
I thought I had fixed it in Dev. Let me take a look at it.

**Comment by Zlatkovsky** [comment]
Bhargav had submitted a pull request, I just hadn't tested/merged-it-in yet.  Will do when I do a couple more fixes (and testing) later this week/weekend

**Comment by Zlatkovsky** [comment]
@WrathOfZombies , see my comment above.  No action is required on your part.

**Comment by Zlatkovsky** [comment]
@cshashwat , the steps above should help you repro it (just log out first and restart the taskpane/webpage), but I also was able to get a local repro, so let me know if you aren't able to repro it and I can show you.
