### ISSUE TITLE
The editor IntelliSense tooltip has a weird font on IE (RichClient)

### ISSUE THREAD

**Issue by yutao-huang** [OfficeDev/script-lab#340]
### Bug Report

- **Host**: Word
- **OS**: Windows 10
- **Browser**: (IE)
- **Environment**: React-Beta

The editor IntelliSense tooltip has a weird font on IE (RichClient). It looks to me like probably Times New Roman or something like that. Definitely different from the one that appears on Chrome.

**Comment by Zlatkovsky** [comment]
If it's quick, let's fix it; if it's not, let's close it.
