### ISSUE TITLE
After importing + trust dialog have extra dark space in footer

### ISSUE THREAD

**Issue by AlexJerabek** [OfficeDev/script-lab#346]
![image](https://user-images.githubusercontent.com/38896772/48805149-73cb0000-eccb-11e8-9833-7e311a505980.png)

**Comment by Zlatkovsky** [comment]
@nico-bellante , it looks like we have a `resizeEditorSaga`.  Maybe you can just dispatch that on dismiss?

function* resizeEditorSaga() {
  if (monacoEditor) {
    monacoEditor.layout();
  }
}

**Comment by nico-bellante** [comment]
I'm going to guess this was only repro-able on IE as it doesn't repro on Chrome standalone.
