### ISSUE TITLE
Takes forever to load, cannot load

### ISSUE THREAD

**Issue by ProfessorJimJam** [OfficeDev/script-lab#368]
i have recorded the video from my machine, you can see in the video uploaded in youtube link below, 

the app cannot load and also please see my office version and OS details,

https://youtu.be/fhCKR4tkIcA

**Comment by Zlatkovsky** [comment]
@ProfessorJimJam , thanks for the report and the detailed video.

It sounds like the same issue as https://github.com/OfficeDev/script-lab/issues/365.  You're the third person to report hitting it.  We will investigate as soon as possible.  For now, I'll close this issue as a duplicate and we can track the progress on the other issue.  The other issue also lists out a workaround step (albeit non-ideal)
