### ISSUE TITLE
Make "run" more obvious?

### ISSUE THREAD

**Issue by Zlatkovsky** [OfficeDev/script-lab#370]
Filing on behalf of a Playground user:

> I was so excited to play with the snippets, but it took me 10 minutes to realize where the Run button was-  I was looking everywhere in the taskpane and finally thought to check the ribbon

**Comment by saunders77** [comment]
Here's the design. The menu triggers on hover and on select of the Run button in the pane. There's nothing selectable in the pane. 

Jakob/Daniel, please confirm. Thanks!
![image](https://cloud.githubusercontent.com/assets/5040375/25288052/a2ea41ea-2678-11e7-81dd-6bf31278763b.png)

Here's the image used in the design:
![run screenshot](https://cloud.githubusercontent.com/assets/5040375/25288064/b4dbef16-2678-11e7-8496-ef5885177eb8.png)

**Comment by Zlatkovsky** [comment]
@saunders77 , please assign to me once you and Daniel agree on the design

**Comment by Zlatkovsky** [comment]
Did the simplest fix possible for now.
It would be nice to have an image there too, such as this:
![run](https://cloud.githubusercontent.com/assets/2230453/25838707/459ab202-3449-11e7-90f3-a8fdb01b505d.jpg)

But not sure how to do it quickly.  So opting for text instructions instead.

**Comment by Zlatkovsky** [comment]
Deployed & live.
