### ISSUE TITLE
Cache the libraries (contents) so that theres never an instance of no intellisense

### ISSUE THREAD

**Issue by nico-bellante** [OfficeDev/script-lab#38]
Either in sessionStorage or localStorage

**Comment by Zlatkovsky** [comment]
LocalStorage runs the risk of overfilling rather easily.  So I don't think we should do that.
For sessionStorage, yeah, we could.  That's what the old Script Lab did, actually.
Let's discuss exactly what you mean, though, and what is the problem we are trying to solve.  There might be other optimizations we could do to get IntelliSense to load faster (e.g., make use of browser cache, only taking in fresh copies once a day -- maybe as a background process, even?; or whatever)

**Comment by gergzk** [comment]
Ls is about 5MB usually so I wouldn’t rely on it unless the intelliaense
files are quite small. I assume this is for cases where the user has
imported custom files?

**Comment by Zlatkovsky** [comment]
Note, we also seem to be doing a double-fetch of libraries by getting the contents and then tossing it away, inside of `packages\editor\src\store\editor\sagas.ts`

```
  const urlContents = yield all(
      urls
        .map(url =>
          fetch(url)
            .then(resp => (resp.ok ? resp.text() : Promise.reject(resp.statusText)))
            .catch(err => {
              console.error(err);
              return null;
            }),
        )
    );
```
