### ISSUE TITLE
Allow arbitrary import URL as long as it points to plain text file with yaml in it

### ISSUE THREAD

**Issue by nico-bellante** [OfficeDev/script-lab#39]
E.g.: https://gist.githubusercontent.com/Zlatkovsky/05a5ede7af7dafadc963229da0edf78b/raw/51f1f48725ad0fea16a39a076d3078876ab73d6b/Custom%2520Functions%2520demo.yaml

**Comment by wandyezj** [comment]
Easy enough. We don't need to worry about every edge case.

Fixed in the latest version of Script Lab.
