### ISSUE TITLE
Create table for what is supported where, with any caveats

### ISSUE THREAD

**Issue by Zlatkovsky** [OfficeDev/script-lab#394]
E.g.,:
- WAC Safari runner doesn't work unless you enable a setting (@nico-bellante , find out from Dan what it is)
- Custom Functions only on PC & WAC, not Mac (due to lack of Script Lab support for now) or iOS (due to lack of platform support for CFs there).

Honestly, it could just be a "known issues" table too, in the README

**Comment by wandyezj** [comment]
The existing office-js documentation should be sufficient.
