### ISSUE TITLE
OfficeHelpers methods are showing up with red underlines

### ISSUE THREAD

**Issue by jakobpn** [OfficeDev/script-lab#397]
![image](https://cloud.githubusercontent.com/assets/13109307/25570308/da847488-2dd8-11e7-9f66-ecd1bca7acdb.png)

**Comment by Zlatkovsky** [comment]
Yes, looks like Bhargav accidentally just broke that.  Will text him momentarily

**Comment by Zlatkovsky** [comment]
(For clarification:  we've added a couple refinements to Office Helpers, and the helpers themselves work fine, but a couple of the arguments were incorrectly marked as non-optional)

**Comment by WrathOfZombies** [comment]
@Zlatkovsky @jakobpn Fixed this. The latest version is 0.6.4.
Please give it a shot.

**Comment by WrathOfZombies** [comment]
@Zlatkovsky for future reference you can just do the fix and up the version number accordingly. and check it in. if the version is different from the previous commit, it will automatically deploy.

**Comment by Zlatkovsky** [comment]
Yep, it works now.  Thanks!
