### ISSUE TITLE
Cancel the renaming of a snippet does not cancel it in editor mode

### ISSUE THREAD

**Issue by maninweb** [OfficeDev/script-lab#413]
Hi there,

while testing, I noticed, that the Cancel-Button on the Info-Dialogue for a snippet has no effect while being in the editor mode, meaning does not do what I would expect as a user. For example, create a new blank snippet and after then, open the Info-Dialogue.

![image](https://cloud.githubusercontent.com/assets/13045898/25779171/707e1adc-3312-11e7-8111-76081b41e9f6.png)

Now change some text, for example like in the screenshot below.

![image](https://cloud.githubusercontent.com/assets/13045898/25779183/a697c9ba-3312-11e7-8189-132f6970844b.png)

If I click on Cancel, I would expect that my changes would be cancelled and that I would see the same data as before I called the dialogue. 

If I go back to my list of snippets, then I see the previous data (Blank Snippet). So it is not saved, what is correct. But from a users' perspective, I think it be better to also revert the change in editor mode. What do you think?

Best,
Mourad

**Comment by Zlatkovsky** [comment]
@WrathOfZombies , is there an easy way of getting "cancel" to invalidate the changes and roll them back in the UI of the editor?

**Comment by Zlatkovsky** [comment]
Actually, today's behavior is somewhat worse than what Mourad describes.  If you cancel but then make any changes to the snippet, the snippet still gets saved with the new (yet cancelled) name.

If it's easy to fix, let's fix it.  Otherwise, let's just remove the "cancel" button...

**Comment by nico-bellante** [comment]
Removed the cancel button in #823
