### ISSUE TITLE
Should runner output snippets with use of `<script async="async" ...>

### ISSUE THREAD

**Issue by Zlatkovsky** [OfficeDev/script-lab#414]
Are there any pros/cons to adding an `async` attribute to the script tags for references (other than Office.js, since there we want the namespace to load before moving on?)

https://www.w3schools.com/tags/att_script_async.asp

**Comment by Zlatkovsky** [comment]
@WrathOfZombies , the change itself is trivial, I just wanted to hear your opinion for why we should or should not do it.

**Comment by WrathOfZombies** [comment]
What's the benefit of the same. We want to load all of the dependencies before running the snippet. Async scripts are useful for lazy loading components or making stuff like telemetry load a little later. Else I'd prefer the blocking approach.

**Comment by Zlatkovsky** [comment]
OK, fair point.  I think I had a rationale, but I don't recall it right now.  Will re-open later if I remember.
