### ISSUE TITLE
Splitting /**@customfunctions */ comment away from function body causes blank success

### ISSUE THREAD

**Issue by nico-bellante** [OfficeDev/script-lab#421]
![image](https://user-images.githubusercontent.com/2230453/49406591-daf4a580-f70a-11e8-999c-c3d8562d08f4.png)

**Comment by gergzk** [comment]
needs to wait on some other custom functions work

**Comment by Zlatkovsky** [comment]
Might be auto-solved by https://github.com/OfficeDev/script-lab/issues/466

**Comment by Zlatkovsky** [comment]
Doesn't seem to matter with the new "custom-functions-metadata" parser.  Closing.
