### ISSUE TITLE
Toolbar in Code pane does not show on Office 2016 MSI

### ISSUE THREAD

**Issue by jakobpn** [OfficeDev/script-lab#426]
Since there are no ribbon commands then it is not possible to run snippets.

![image](https://cloud.githubusercontent.com/assets/13109307/26251379/e3720672-3c61-11e7-82c5-8e0a2f9a4dea.png)

![image](https://cloud.githubusercontent.com/assets/13109307/26251383/e754b406-3c61-11e7-8cd6-7b68237edd8f.png)

**Comment by Zlatkovsky** [comment]
It looks like for some reason, none of the Fabric icons loaded.

One thing to check would be:  do the Fabric icons load in a regular browser session on IE on that computer. ?  I.e., try loading https://script-lab.azureedge.net/?mode=web.

That is a key bit of information we need.  @jakobpn , assigning back to you to find out.

**Comment by jakobpn** [comment]
Thx. I will ask the user to send us the requested screen shot.

**Comment by jakobpn** [comment]
Here is what the user is getting in the browser:

![ie](https://cloud.githubusercontent.com/assets/13109307/26315247/57f567ae-3ec5-11e7-9876-f1f16903c704.png)

**Comment by Zlatkovsky** [comment]
OK, thanks.  I believe what we need next is a Fiddler trace, and/or a view of the network tab in IE's F12 tools.  @WrathOfZombies has more experience with this sort of thing, though I'd love to learn how he debugs these things.  Bhargav, adding you as a co-assignee as well.

BTW, would also be useful to know if the customer sees the same issue in the browser **on a different browser** (e.g., Chrome, Firefox)

**Comment by jakobpn** [comment]
Icons are shown in Chrome
![chrome](https://cloud.githubusercontent.com/assets/13109307/26363170/21893f94-3f95-11e7-92ff-77e2e9eb9320.png)

**Comment by Zlatkovsky** [comment]
@WrathOfZombies , thoughts on how to debug this?

**Comment by WrathOfZombies** [comment]
The IE looks different. Is this a Windows Server machine and does it have some script execution restrictions on IE?

**Comment by Zlatkovsky** [comment]
@WrathOfZombies , are you referring to the black bar at the top of IE?  I think that's just the print-screen tool (or having a screen-recording/screen-sharing tool running at the same time...  I've seen something similar happen before on my machine, don't remember the exact circumstance)

**Comment by WrathOfZombies** [comment]
Ask @Zlatkovsky pointed out, we'd need fiddler logs for both chrome, IE and Agave sessions. Also console.logs for any errors would help. If there are too many exceptions, then the telemetry user ID.

I use the fiddler logs to see if the Agave related scripts or bornholm scripts are loaded correctly or not and whether they are causing any issues. Then I'd need to see the console.logs to see if there are any exceptions and if so why. Lastly the telemetry data tells me if there's a corrupt state to lifecycle related issue. Even if that doesnt explain, I'll need to get hands on and see for myself.

**Comment by WrathOfZombies** [comment]
Oh ok.. then we need to debug as per my reply above.

**Comment by jakobpn** [comment]
The user accessed Excel and Script Lab through a remote desktop session from his Mac.

**Comment by bohtho** [comment]
I have this same issue in my script lab pane in Excel 2016 in the corporation I work at. No icons in the pane tool bar. Same when loading https://script-lab.azureedge.net/?mode=web in IE 11.1770.14393.0

**Comment by stevec-NC** [comment]
same issue in Word 2016 MSI version.
No ribbon in Word.
Ribbon buttons do exist on the url above in Chrome (latest).

![word_2016](https://user-images.githubusercontent.com/33737950/32923198-24037bb8-cb86-11e7-9cf4-a1e593724732.png)
![web_ribbon](https://user-images.githubusercontent.com/33737950/32923199-255574a8-cb86-11e7-8e7c-0c1154e9728f.png)
![image](https://user-images.githubusercontent.com/33737950/32923226-549028bc-cb86-11e7-85a2-2b8fe35ea55b.png)

**Comment by Zlatkovsky** [comment]
This is an issue with Internet Explorer settings, which I've once seen happen on another two computers (but no discernible pattern for why it happens...).  Please see the image on https://github.com/OfficeDev/office-ui-fabric-core/issues/987#issuecomment-308271822 for a quick fix under IE settings.

**Comment by stevec-NC** [comment]
Agree it would be an IE problem if I was using IE...
I use Chrome as my primary browser - as the SS show the link works correctly for browser access, it is NOT working in Word.

**Comment by Zlatkovsky** [comment]
On Office for PC, the sole rendering engine for Office Addins *is* Internet Explorer.  This is irrespective of what your default browser is.

If I understood your screenshots correctly, the places it’s not working are Excel and Word on your PC, correct?  And @bohtho likewise mentioned that it’s not working for them on both Office and inside of Internet Explorer proper.

**Comment by stevec-NC** [comment]
So you are saying I have to now download and install IE to fix a problem with a Word add-in?

**Comment by Zlatkovsky** [comment]
@stevec-NC , if you were to open Internet Explorer and browse to http://fontawesome.io/icons/, do you see icons there?  What about going to https://script-lab.azureedge.net/#/edit/excel in IE?

I do think it's some sort of internet configuration issue...

**Comment by stevec-NC** [comment]
OK it's now working with no changes made .... the control bar doesn't appear as a ribbon but inside the script box area itself.
Getting code to actually work is then next issue, so far none of the samples work...

**Comment by Zlatkovsky** [comment]
@stevec-NC , ok, that's progress :-)

For the ribbon not appearing:  if you are on an MSI version of Excel 2016 (i.e., not subscription O365), that makes sense, since the original 2016 did not have support for Add-in Commands (ribbon).

For samples not working -- please post a new issue with details re. which snippet(s) isn't/aren't working for you, and what is the error you're getting.

Thanks!

**Comment by bohtho** [comment]
It's due to a common security setting in IE in corporations (not downloading external fonts), so could you include the icons/fonts in question or fall back to another solution for the toolbar in such cases ?

**Comment by Zlatkovsky** [comment]
Fair enough, opened a new issue for it:  https://github.com/OfficeDev/script-lab/issues/735.

**Comment by Zlatkovsky** [comment]
@bohtho , just to clarify:  were you having the same issue even if you opened https://script-lab.azureedge.net/#/edit/excel in regular Internet Explorer, outside of an Add-in?  (And what about the Edge browser?)

If you instead opened Outlook Online (e.g., https://mail.office365.com if you have an O365 subscription; or just https://outlook.com for consumer versions), do you also see a font issue there?

If you don't mind, please reply to those questions on the newly-opened #735 issue.  I had to put the questions here since I couldn't at-mention you on the new issue, without you having already responded there.

Thanks!
