### ISSUE TITLE
Unable to open runner in Excel Online in Chrome on Mac

### ISSUE THREAD

**Issue by jakobpn** [OfficeDev/script-lab#429]
Getting "chasing dots".

**Comment by Zlatkovsky** [comment]
Just runner, not editor?  What about other snippets (blank one)?

**Comment by Zlatkovsky** [comment]
Reassigning back to you for more info

**Comment by jakobpn** [comment]
Yes, just runner. Code pane opens OK.

**Comment by Zlatkovsky** [comment]
@jakobpn , blank snippet as well or just a specific one?

**Comment by jakobpn** [comment]
I am able to open the runner now.
