### ISSUE TITLE
No Ribbon Tab after installing Script Lab

### ISSUE THREAD

**Issue by ManfredH** [OfficeDev/script-lab#435]
After installing Script Lab in Excel 2016 I can code an run office-js scripts with the Script Lab window. However the ribbon tab "Script Lab" is missing. Excel revision is Excel 2016 MSO 16.0.4498.1000 32-Bit.

**Comment by Zlatkovsky** [comment]
@ManfredH , Add-in Commands (ribbon) is only available in Office 365 (the subscription-based version of Office), not in the original Office 2016 incarnation.

See more at https://dev.office.com/docs/add-ins/develop/office-versions
