### ISSUE TITLE
Use browser instead of the modal to open

### ISSUE THREAD

**Issue by Hongbo-Miao** [OfficeDev/script-lab#436]
Right now on macOS, when I clicked `Reference Docs` or `Ask the Community`, it opens a modal.
I have to close the modal to continue using Excel.
Maybe we should just use the browser to open it.

![image](https://cloud.githubusercontent.com/assets/3375461/26607777/0ac7af08-454d-11e7-9fef-8ae0ac379c33.png)

**Comment by jakobpn** [comment]
And there are no scroll bars which makes in impossible to read the content of the page.

**Comment by Hongbo-Miao** [comment]
Yeah, the mouse scroll and touchpad does not work on this page.

**Comment by Zlatkovsky** [comment]
Duplicate of https://github.com/OfficeDev/script-lab/issues/402.
But, @saunders77 , still (doubly) worth doing...
