### ISSUE TITLE
Tutorial does not download the file

### ISSUE THREAD

**Issue by Reezaali** [OfficeDev/script-lab#438]
Repro steps:
1. Click Tutorial button.
2. Click link "script-lab-tutorial.xlsx".

Result: Nothing happens.
Expected Result: File starts to download. 

Thanks,
Reeza.

**Comment by Zlatkovsky** [comment]
@Reezaali , are you sure _really nothing_ happens?  I've seen cases in the past where IE, or your default browser, appears silently appears behind a window.  I don't think I've ever seen it fail outright...

**Comment by Zlatkovsky** [comment]
No repro/answer. Closing for now.
