### ISSUE TITLE
Blog post for the next update of the README.md

### ISSUE THREAD

**Issue by jakobpn** [OfficeDev/script-lab#449]
https://medium.com/leonardo-xavier/script-lab-novo-add-in-da-microsoft-f8aee5bf0dd2

**Comment by Zlatkovsky** [comment]
Fixed with https://github.com/OfficeDev/script-lab/commit/0f48bbc5510969d965c557ade4290c4f10dbf39e.

@jakobpn , feel free to make the edits yourself for these sorts of things, too...
