### ISSUE TITLE
Set expiry date in response cache headers for Script Lab resources

### ISSUE THREAD

**Issue by dsaunders45459** [OfficeDev/script-lab#459]
Running Google page speed test against Script lab shows some performance issues:
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fscript-lab.azureedge.net

We need to be setting response cache headers for JavaScript/CSS resources, and then use chunk hash to force the browser to download the latest resource when they change. Without setting the expiration time the browser may request the resource from the server often, without the resource actually changing and making Script Lab slow to load.

**Comment by Hongbo-Miao** [comment]
And turn on gzip can help a lot. My last project reduce from 5MB to around 200kb.

**Comment by Zlatkovsky** [comment]
Related to https://github.com/OfficeDev/script-lab/issues/455

**Comment by WrathOfZombies** [comment]
@Hongbo-Miao GZip is already enabled on the project. The headers are sent and the compression is working. What we do need is modifying the project build system to utilize AOT. That's going to give the biggest perf improvement. Could you help with that?

@dsaunders45459 given that these are served from a CDN, there's not much worry around the resource being requested again.
