### ISSUE TITLE
Script Lab fails to clear document body on Word Online

### ISSUE THREAD

**Issue by kenual** [OfficeDev/script-lab#460]
Script Lab fails to clear document body on Word Online --

Script Lab public gist link

https://gist.github.com/kenual/31548c30cfb12004177af89d44effbe0

The same script works fine inside Script Lab on Word 365 Win32 Version 1706

## Expected Behavior

After base64 file is inserted, context.document.body.clear() should succeed on Word Online just like Word on Windows.

## Current Behavior

Script Lab shows Office exceptions running on Word Online

context.document.body.clear() should work on Word Online

## Steps to Reproduce (for bugs)

1. Open Script Lab on Word Online
2. Copy github public gist 

https://gist.github.com/kenual/31548c30cfb12004177af89d44effbe0

and paste into Script Lab

3. Click Run  to execute the Word JS block

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):

## Useful logs

- [ ] Fiddler traces
- [ ] Console errors
- [ ] Screenshots
- [ ] Clip or GIFs

**Comment by Zlatkovsky** [comment]
@kenual , is this a Script Lab bug or an Office.js bug?  It sounds like almost certainly the latter, which you happen to have found in Script Lab (but would likewise have found if you were building the add-in using Visual Studio or any other means).

Adding @JuaneloJuanelo , who can help route the bug to the appropriate developers.  @JuaneloJuanelo , please close this issue once we have something else tracking this.

**Comment by kenual** [comment]
@Zlatkovsky Thank you for looking into this issue!  This appears to be an Office.js bug on Word Online. Script Lab makes it easy to valid problems on different platforms and report issues via public gist.

@JuaneloJuanelo I would like to have this Office.js bug routed to the correct repository. Please let me know where I can keep track of this problem.

**Comment by Hongbo-Miao** [comment]
Hi @kenual I think you can report here https://github.com/OfficeDev/office-js/issues

**Comment by Zlatkovsky** [comment]
@kenual , once you've filed the issue on the repo that Hongbo mentioned, please put a reference to it here and then close this Script Lab bug.  Thanks!

**Comment by kenual** [comment]
Thank you all for helping out! I've created tracking issue

https://github.com/OfficeDev/office-js/issues/1

on Office JS repo, thus closing this Script Lab issue.
