### ISSUE TITLE
BLOCKER:  bornholm-edge deployment is broken (unless in in-private window)

### ISSUE THREAD

**Issue by Zlatkovsky** [OfficeDev/script-lab#469]
@dsaunders45459 , @cshashwat , it looks like accessing the bornholm-edge site in IE 11 (browser or add-in, doesn't matter) is showing broken (missing) UI when not in in-private browser mode.  I am not sure if it's a matter of having snippets already, or of having cached files; but in either case, it's not working.  We need to make sure it doesn't make it in like that to insiders/prod (possibly by implementing the hashing & cache-busting first).

This is happening to me on both my home machine and laptop.  I am not going to flush my cache yet, so that I can remain a repro case.  Let me know if you'd like me to try something.

![image](https://user-images.githubusercontent.com/2230453/27848877-5ad7e136-60fd-11e7-9f3d-b2e22771c9d2.png)

**Comment by Zlatkovsky** [comment]
Adding @WrathOfZombies too, in case he can offer some advice.  Just launching F12 didn't reveal much.  No console errors, though a suspiciously-empty initial root state...

![image](https://user-images.githubusercontent.com/2230453/27848925-c843fe3a-60fd-11e7-9106-aa2cfb2c1cd9.png)

versus the in-private one:

![image](https://user-images.githubusercontent.com/2230453/27848954-0ed8a0ee-60fe-11e7-86c0-f3ee574016e2.png)

**Comment by Zlatkovsky** [comment]
I should also mention that this issue was happening even before I merged in #468.  So it's not the new string changes.

**Comment by dsaunders45459** [comment]
I think this is probably related to an n-1 browser cache issue with the JavaScript resources, and not to localStorage. I can repro fairly often using the following steps on IE 11, although it doesn't repro on Chrome. The browsers have different cache policies when the response headers are not being set, so this is probably why I can only hit it in IE. @cshashwat can you look into the chunk hashing next and wait for it to deploy the changes to prod.

Clear IE cache
Fiddler "urlreplace bornholm-edge.azurewebsites.net/ script-lab.azureedge.net/"
Navigate to https://bornholm-edge.azurewebsites.net/ in IE
Click on Excel theme icon
Click on Basic API call
Save the snippet
Fiddler urlreplace clear
Close/reopen browser and renavigate to https://bornholm-edge.azurewebsites.net/ (may be optional)
ctrl + r to reload page. Most of the time the page will fail to load here or no-op after clicking Excel icon again.
