### ISSUE TITLE
Closing the GitHub Login window and trying to login again does not work until I refresh the Code Pane

### ISSUE THREAD

**Issue by maninweb** [OfficeDev/script-lab#470]
Hi there,

I noticed that if I close the GitHub Login Window, I can not recall the GitHub Login Window until I close the Code pane and reopen it again. For reproducing, please follow the steps below.

First, I deleted my Internet Explorer Cache (Ctrl + Shift + Del). After then I started Script Lab Version 1.1.0 and opened the Script Lab Code pane in Excel 2016, latest Slow Insider Build (Note: the issue is also reproductible in Word and PowerPoint). Then, I directly clicked on the Hamburger menue and I get this view.

![image](https://user-images.githubusercontent.com/13045898/27911843-e0a0072c-625a-11e7-8bd2-ca0aa041af7f.png)

When clicking on the icon for signing in to GitHub, the GitHub login window appears (in the following screenshot resized)

![image](https://user-images.githubusercontent.com/13045898/27911925-35f51604-625b-11e7-9df4-a5c7dc16215e.png)

If I then click again on the icon for signing in to GitHub, nothing happens. If I try to login into GitHub by going to the section "My snippets", this also does not work. I have to close the Code pane and reopen it for getting the login window again.

Also a message can be found in the message queue: "Failed to sign in to GitHub." On my second try to login to GitHub, no message is thrown.

Hope, that I have not overseen an already posted issue about this.

Best,
Mourad

**Comment by Zlatkovsky** [comment]
Assigning to Shashwat.  It's a known class of issues that we have around Error-Handling, where the event pipe gets closed on failure.

@cshashwat , I recommend we do another of those auto-reload quick fixes, (but only after the other few things that we want to get into the deployment queue), and then address it holistically after the view URL / sharing feature.

**Comment by WrathOfZombies** [comment]
@Zlatkovsky @cshashwat I'd advice look towards a solution instead of a quick fix as this problem would ultimately need to be solved.

**Comment by cshashwat** [comment]
Have verified that this issue is now fixed in Excel, Word and PowerPoint, closing it for now.
