### ISSUE TITLE
Can get into strange behavior with using @customfunctionS instead of @customFunction

### ISSUE THREAD

**Issue by nico-bellante** [OfficeDev/script-lab#477]
I actually fooled myself with this one for quite a while trying to figure out why my custom functions weren't being registered.

![image](https://user-images.githubusercontent.com/35939126/49838148-1bcd6980-fd5e-11e8-94c4-7730ce17bdf5.png)

Note how the run button is a register button.

But if you were to click the register button, it wouldn't show those functions as registered custom functions.

**Comment by Zlatkovsky** [comment]
Still repros.  Need to do a "full word" search to make sure there isn't other things (e.g., "s" suffix) at the end.
Also need to make sure that don't end up in blank state:

![image](https://user-images.githubusercontent.com/2230453/53525807-7e99eb80-3a97-11e9-8640-7cd6ea0a6c66.png)
