### ISSUE TITLE
MessageBar issue

### ISSUE THREAD

**Issue by nico-bellante** [OfficeDev/script-lab#481]
There was a bugfix a while ago tha switched the height of `.message-bar.active` to auto instead of 4.8rem. This messes up with the animations. If it is set to 4.8rem, then it breaks when messageBar is in multi-line mode..

**Comment by Zlatkovsky** [comment]
I'm not clear what the work involved here is, or what its estimate is.  Leaving without milestone so we can triage it.

**Comment by Zlatkovsky** [comment]
@nico-bellante , is there any remaining work here?...

**Comment by wandyezj** [comment]
Obsolete.
