### ISSUE TITLE
Making importing any libraries easier (original title: "'require' is not defined")

### ISSUE THREAD

**Issue by gergzk** [OfficeDev/script-lab#482]
### Bug Report

- **Host**: Excel win32
- **OS**: Win10
- **Browser**: 
- **Environment**: react alpha

#### Expected behavior:

I shuold be able to import an npm package that uses 'require'

#### Actual behavior:

'require' is not defined,https://unpkg.com/url@0.11.0/url.js,24,1,ReferenceError: 'require' is not defined

#### Steps to Reproduce:

Create a new sample in SL. 
Add 'url' in imports (this points to https://www.npmjs.com/package/url)
import * as url from 'url' in the source code
Run
Above error appears.

**Comment by iabukai** [comment]
How can I use npm packages like 
request-promise or fs  without these ? 
I tried on the libraries panel 
@types/request-promise
@types/fs

But how can I reference them on the Script panel ?

**Comment by Zlatkovsky** [comment]
@iabukai, for libraries to work with Script Lab, they need to be ideally already pre-compiled for the browser.  See more on https://github.com/OfficeDev/script-lab-2017/pull/391/files#diff-04c6e90faac2675aa89e2176d2eec7d8R99

**Comment by wandyezj** [comment]
Use of libraries is an edge case for Script Lab. Script Lab is for customers to play with office.js APIs

If customers need to use libraries they should build a full [Add-In](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/develop-overview).

Customers can create and host their own Add-In on GitHub, for example see the [Build Add-In](https://github.com/wandyezj/website-react-extension) you can sideload the [manifest](https://github.com/wandyezj/website-react-extension/blob/main/manifests/production.xml).
