### ISSUE TITLE
Perhaps use LastOpened over LastModified

### ISSUE THREAD

**Issue by nico-bellante** [OfficeDev/script-lab#484]
Aaron pointed out a scenario the other day that seemed awkward. 

1. Open Solution 1.
2. Modify Solution 1.
3. Open Solution 2.
4. Click Run (that transfers this pane to the runner)
5. Click back button. 
6. Solution 1 is shown as it was the last modified.

One way to solve this would be to keep a last opened property.

This could either be a global key that holds the solution last opened, or a property on each solution that has a timestamp for whenever a solution was opened. I think the latter sounds like it might be better as we could use this data in ordering the backstage once that functionality is in place.

**Comment by gergzk** [comment]
Let's use LastOpened, that is exactly what we care about in this scenario.
