### ISSUE TITLE
Unlocalized word in the switch environment dialogue

### ISSUE THREAD

**Issue by maninweb** [OfficeDev/script-lab#494]
Hi there,

from the About dialogue, I can now switch the environment to another one, that's cool. However, the title of the environment switcher dialogue includes the unlocalized string `to`.

![image](https://user-images.githubusercontent.com/13045898/28110568-1dea29a4-66f3-11e7-951c-1f2dc586ac67.png)

It can be found in `about.ts` within the code block starting with `let changeEnvironmentResult`. Would it be possible to also put the string `to` into the language files? Or, as a suggestion, have something parametrized like "Switch from _VAR_1 to VAR_2"? Thanks :-)

Best,
Mourad

**Comment by Zlatkovsky** [comment]
Thanks for the find.  @cshashwat , please add the string and then, as with the others, re-open the #472 issue making note of the new string, so that Mourad can translate it.  Thanks!

**Comment by maninweb** [comment]
Hi, for me this issue is solved within the last Insider Version, thanks :-)
I did not close this issue, as I prefer someone of you do this.

**Comment by Zlatkovsky** [comment]
Closing.  By the way, we had intended to push to production this week, but found an issue that needs to be resolved first.  So, Dan and Shashwat will work on getting production updated early next week.
