### ISSUE TITLE
Use sentence casing in Share menu

### ISSUE THREAD

**Issue by jakobpn** [OfficeDev/script-lab#495]
![image](https://user-images.githubusercontent.com/13109307/28128094-767aa5e0-66e3-11e7-9d9e-ab9d7b8b5322.png)

Change "New Public Gist" to "New public gist"
Change "New Secret Gist" to "New secret gist"
Change "Update Existing Gist" to "Update existing gist"

All other menu items are using sentence casing.

**Comment by Zlatkovsky** [comment]
@cshashwat , is this one closed now?  Please close the issues once the environment that they are targeting has received the update.

I also like to use the "resolved-awaiting-prod-deployment" label, at least for prod ones.  Please close any issues marked with that, once you and @dsaunders45459 push to production next week.
