### ISSUE TITLE
Pressing "run" when viewing Custom Function leads to "No snippet to run"

### ISSUE THREAD

**Issue by Zlatkovsky** [OfficeDev/script-lab#496]
Expected behavior (which I think we had once?) was for it to redirect to the dashboard.

![image](https://user-images.githubusercontent.com/2230453/50463173-d785c000-093e-11e9-9821-4f9a97a2facd.png)

**Comment by nico-bellante** [comment]
I'm blocked on setting up a repro for this issue due to:
![image](https://user-images.githubusercontent.com/35939126/51141040-f7e9c180-17fc-11e9-8af3-b14eadd3810b.png)

**Comment by Zlatkovsky** [comment]
Doesn't seem to repro anymore.  Closing.
