### ISSUE TITLE
Loading dots don't display correctly in a row - Insiders

### ISSUE THREAD

**Issue by kevishi** [OfficeDev/script-lab#496]
Using the default size of the add-in pane, the loading dots don't display correctly

![capture](https://user-images.githubusercontent.com/9515715/28131420-a9c564de-66ee-11e7-8d3b-15c4b52cd726.PNG)

Tested on both 1920x1080 and 1920x1200 with various window sizes.

**Comment by Zlatkovsky** [comment]
@cshashwat , this used to be an issue on the Mac, but not on desktop or online.  Could you please take a look?
