### ISSUE TITLE
One "beta" ribbon is enough

### ISSUE THREAD

**Issue by jakobpn** [OfficeDev/script-lab#497]
I think we are overdoing it with 2 ribbons. I suggest we simplify and only show the ribbon to the right.

![image](https://user-images.githubusercontent.com/13109307/28131842-03a7baaa-66f0-11e7-931a-8c9047ea007d.png)

**Comment by cshashwat** [comment]
@Zlatkovsky what's your opinion on this? The justification for two was that the user's eyes might automatically go to one side of the screen vs the other, but in the default add-in pane, it seems like one might be enough.
