### ISSUE TITLE
"No snippet to run" issue, part II

### ISSUE THREAD

**Issue by Zlatkovsky** [OfficeDev/script-lab#502]
Related to #496 , but even weirder:

![image](https://user-images.githubusercontent.com/2230453/50491239-2aef2100-09c6-11e9-832c-39bfea35109d.png)

Repro:
1. Create a CF function and open dashboard
2. Create a regular snippet
3. Press "run".

Get the paradoxical issue above.

@nico-bellante , any ideas?

**Comment by nico-bellante** [comment]
I'm blocked on setting up this repro due to:
![image](https://user-images.githubusercontent.com/35939126/51141116-29fb2380-17fd-11e9-8c36-36e23262859d.png)

**Comment by Zlatkovsky** [comment]
Doesn't seem to repro anymore.  Closing.
