### ISSUE TITLE
Update to latest Mac-happy Monaco

### ISSUE THREAD

**Issue by Zlatkovsky** [OfficeDev/script-lab#506]
Work with someone on the platform team, to investigate why Monaco versions newer than 0.10.1 were having focus issues on the Mac.

Depending on the outcome, either:

1. Upgrade to latest Monaco, (assuming the platform issue can get fixed and shipped out quickly)
2. Work with Monaco team to implement a fix (assuming it can be done quickly)
3. Create mechanism for loading different versions of Monaco depending on office host (< 4 hours of work, though need to be careful going forward to avoid issues if there are differences in API signatures/behavior).

If it's possible to remove the Mac-specific version of Monaco and have everyone share the same version, that would obviously be even better.

**Comment by Zlatkovsky** [comment]
Note: this is more urgent, now that issue #514 has been discovered, which automagically goes away with the newer Monaco...  Adding "blocker" to remind us of that and moving forward a milestone.

**Comment by gergzk** [comment]
So this means we're stuck between a really broken Monaco in some cases, or a really broken Mac experience in the other?

**Comment by Zlatkovsky** [comment]
@gergzk , yeah, it seems like not the most fantastic situation to be in.  We need to investigate ASAP, will try to get Dan's help once he's back on Jan 2nd.
In the meantime, I'm just about done with a fix that loads the newer Monaco for the rest of the clients.  I'll send a PR momentarily.

**Comment by gergzk** [comment]
Yeah I think we'll need the host-dependent version then. Even if we get the core issue figured out fast, it'll take a while to deploy that to all the clients.
