### ISSUE TITLE
config from IEnvironment has the wrong TypeScript type definition

### ISSUE THREAD

**Issue by dsaunders45459** [OfficeDev/script-lab#506]
config is defined as an IEnvironmentConfig but it is actually a different type. This causes us not to be able to get intellisense or the linter to work properly.

interface IEnvironment {
    devMode?: boolean;
    build?: {
        name: string;
        version: string;
        timestamp: string;
        author: string;
        humanReadableTimestamp: string;
    },
    config?: IEnvironmentConfig
    host?: string,
    platform?: string,
    PLAYGROUND_ORIGIN?: string,
    PLAYGROUND_REDIRECT?: string
}

interface IEnvironmentConfig {
    name: string,
    clientId: string
    instrumentationKey: string,
    editorUrl: string,
    tokenUrl: string,
    runnerUrl: string,
    feedbackUrl: string,
    samplesUrl: string
}

let { config } = PLAYGROUND;

The actual type for config:
const config: {
    [x: string]: any;
    local: {
        [x: string]: any;
        name: string;
        clientId: string;
        instrumentationKey: any;
        editorUrl: string;
        tokenUrl: string;
        runnerUrl: string;
        samplesUrl: string;
        feedbackUrl: string;
    };
    edge: {
        [x: string]: any;
        name: string;
        clientId: string;
        instrumentationKey: string;
        editorUrl: string;
        tokenUrl: string;
        runnerUrl: string;
        samplesUrl: string;
        feedbackUrl: string;
    };
    insiders: {
        [x: string]: any;
        name: string;
        clientId: string;
        instrumentationKey: string;
        editorUrl: string;
        tokenUrl: string;
        runnerUrl: string;
        samplesUrl: string;
        feedbackUrl: string;
    };
    production: {
        [x: string]: any;
        name: string;
        clientId: string;
        instrumentationKey: string;
        editorUrl: string;
        tokenUrl: string;
        runnerUrl: string;
        samplesUrl: string;
        feedbackUrl: string;
    };
}
We should be able to export the variable from a TypeScript file to get intellisense.

In our code we have to reference the different environments using config['insiders'].name which has no type checking. We should be able to use config.insiders.name.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):

## Useful logs

- [ ] Fiddler traces
- [ ] Console errors
- [ ] Screenshots
- [ ] Clip or GIFs

**Comment by Zlatkovsky** [comment]
Putting it as "v1.1 patch" in the sense that that sooner is better, so I don't want it lost in the giant 1.4 list.  But feel free to do when it makes sense, there is no real hurry per se.

**Comment by Zlatkovsky** [comment]
@dsaunders45459 , I'm taking care of this one now (needed to as part of doing another work item)
