### ISSUE TITLE
Can't resize console?

### ISSUE THREAD

**Issue by sancarn** [OfficeDev/script-lab#515]
I have a small laptop which means that the console doesn't actually fit on the page given it's current format. Only way to see stuff is by zooming out but then text becomes too small to see anything.

**Comment by Zlatkovsky** [comment]
@sancarn , thanks for the feedback.  Yes, the console resizing (which was available in the 2017 version of Script Lab) is something we already got a feedback on, and definitely want to bring back soon.

One possibility is to use <https://www.npmjs.com/package/react-split-pane>.  We need to figure out how to do keyboard accessibility for it, however.

In the meantime, if it's a blocker for you, you can always switch to the 2017 version using the instructions at https://github.com/OfficeDev/script-lab/blob/master/README.md#2017.

**Comment by sancarn** [comment]
Thanks for mentioning that you can switch back! I wouldn't have noticed otherwise!

**Comment by Zlatkovsky** [comment]
We should have a blog post soon (next couple days) that will let folks know about the new Script Lab and also include the opt out instructions.

But obviously, any future investment will be in the new Script Lab, and already there are a lot of improvements it offers over the old one (esp. the fast reload of snippets).  So if you are able to use it, we'd love to hear how it's going for you :-).  And we'll try to get that console resizing addressed in the near future.

**Comment by sancarn** [comment]
It also should be noted that I found today you can open F12 devtools instead of the live console:

https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-add-ins-using-f12-developer-tools-on-windows-10

If you want to access the global scope of the addin then use:

```
var win = document.getElementById("user-snippet").contentWindow
console.log(win.someGlobalVar)
```

**Comment by Zlatkovsky** [comment]
@sancarn , here is a picture for inspiration.  Note how you also get to see the compiled-to-javascript source code (from the "async/await" statement -- which is either frightning or cool or a bit of both, depending on your perspective) :-)

![image](https://user-images.githubusercontent.com/2230453/50578243-e57a8b80-0deb-11e9-9d49-bc3bd40fd643.png)

**Comment by sancarn** [comment]
Good point about using debugger! That is much easier! :) I quite often step through the code and did already notice the interesting generator based async/await compiled syntax. Not exactly how I would do async/await but cool never the less! 👍 

Would be cool if long-term ScriptLab could have an equivalent debugger e.g. `ScriptLab.Debugger()` which launches a Step-By-Step debugger which preserves the ES6 code representation via the babel mapping.

Could be based on numerous existing JavaScript parsers written in javascript:

**Probably the most up to date**
https://github.com/Siubaak/sval

**Others:**
https://github.com/NeilFraser/JS-Interpreter
https://github.com/marten-de-vries/evaljs
https://github.com/eiriklv/tailspin
