### ISSUE TITLE
Consider updating to latest Monaco

### ISSUE THREAD

**Issue by Zlatkovsky** [OfficeDev/script-lab#519]
With #518 , updating Monaco back to "0.14.3", which is a "last known good" that we'd tested for quite some time.

However, we should consider migrating forward to 0.15.6 or whatever is latest at that point (https://github.com/Microsoft/monaco-editor/blob/master/CHANGELOG.md), as long as we do it in `master` and give it a few days.  **We should also consider using the testing framework that @nico-bellante has been investigating to see if a regression like #514 could have been prevented.**

**Comment by gergzk** [comment]
In addition to whatever smoke testing, make sure to run Keros on each of the screens as well. I'll send a link, it's a chrome extension.

**Comment by Zlatkovsky** [comment]
Dup of https://github.com/OfficeDev/script-lab/issues/506
