### ISSUE TITLE
When run linter in CI environment, should run with severity "error", not "warning"

### ISSUE THREAD

**Issue by Zlatkovsky** [OfficeDev/script-lab#522]
I.e., should not let me accidentally commit a `debugger;` statement, the way it did here:

https://github.com/OfficeDev/script-lab/pull/518/commits/54588a542baeb49d447ea58390fae2f4e76bed45

You can see it outputting the warning in the log, too:
https://travis-ci.com/OfficeDev/script-lab/jobs/167576415#L1215

So we just need to make the linter override the default severity and run with error severity

**Comment by Zlatkovsky** [comment]
Actually, this might be a little less trivial.  It looks like tslint commandline doesn't let you specify a severity override.  So we would instead need to have it either modify the "tslint.json" files (but then for local running not on CI, how do we make sure we don't check in as such?), or have it always create a shadow copy of the tslint files as the "effective" tslint config, or... something

**Comment by wandyezj** [comment]
Obsolete.
