### ISSUE TITLE
Feature: Permanently save snippets

### ISSUE THREAD

**Issue by Zlatkovsky** [OfficeDev/script-lab#526]
There have been numerous requests to offer more permanent storage for snippets (be it a GitHub repo, a OneDrive folder, etc.)

We need to think through it.

In the meantime, closing the following two issues from the old repo, to track it in this new one:
- https://github.com/OfficeDev/script-lab-2017/issues/864
- https://github.com/OfficeDev/script-lab-2017/issues/394

**Comment by wandyezj** [comment]
Obsolete. Snippets can be copy and pasted to be stored anywhere.
