### ISSUE TITLE
Missing hamburger (when no local snippets) looks odd

### ISSUE THREAD

**Issue by Zlatkovsky** [OfficeDev/script-lab#531]
Today's experience removes the hamburger (while leaving the space for it and having it be hoverable/underlined) if you have no local snippets.  See below.

Though it serves the necessary function -- of preventing you from seeing an empty editor that has no snippet open -- the current treatment feels buggy.  I have felt this way for some time, and recently it was pointed out by another user as well.

@yolena , can you think of a way of making it not feel like a bug?

![image](https://user-images.githubusercontent.com/2230453/50611940-1f4f9e80-0e8d-11e9-9e71-d03e1ee4ee28.png)

![image](https://user-images.githubusercontent.com/2230453/50612901-99355700-0e90-11e9-96da-11f7d5642f3e.png)

**Comment by Zlatkovsky** [comment]
Alternatively, @nico-bellante , is there a way to just get that item to render with CSS style "visibility: hidden"?  Would making it inactive be good enough?...

This is trivial to do with basic CSS, but might be less trivial with plumbing it in through React/FabricReact...

**Comment by gergzk** [comment]
Let's do the simple thing and just make it not feel like a button (no hover, no click, visibility hidden)

**Comment by nico-bellante** [comment]
In order to keep the space, but not have it be actionable, I think it would either be hacky and/or longer than 1 hour. To make the space disappear would be a couple seconds, but that also feels even weirder IMO, at least for the nav menu. for the Pivot, I could see us just hiding the space.
