### ISSUE TITLE
Consolidate build scripts for editor + runner, and have both output commit and deployment info to console

### ISSUE THREAD

**Issue by Zlatkovsky** [OfficeDev/script-lab#533]
Today, the **editor** has its own "build.js" that sets

```
  `export REACT_APP_COMMIT='${TRAVIS_COMMIT}'`,
  `export REACT_APP_LAST_UPDATED='${new Date().toUTCString()}'`,

  'export CI=false', // TODO: (nicobell) undo this... this is a hack to suppress the following warning: ...
```

Whereas the **runner** doesn't have those environmental variables.

Correspondingly, the **editor** has a `.env.development` whereas the **runner** doesn't.

I think we should consolidate, creating a common build script for both.  And we should further make it so that during the loading of Script Lab (e.g., maybe during the dynamic script loader), we display the same info that we display under "About", dumping it onto the console.  That way, even if the editor errors out when loading, we can see what version the user had in the debugger.

**Comment by wandyezj** [comment]
Obsolete.
