### ISSUE TITLE
Server should have a "/version" route so we can know that it's deployed correctly

### ISSUE THREAD

**Issue by Zlatkovsky** [OfficeDev/script-lab#534]
We should replace today's <https://script-lab-server.azureedge.net/hello> with a more useful response.
Similar to what the old Script Lab server had:

http://bornholm-runner.azurewebsites.net/version

```
{
    "build": {
        "name": "Script Lab Runner",
        "version": "1.1.0",
        "timestamp": 1545030577265,
        "humanReadableTimestamp": "2018-12-17 07:09 am UTC",
        "author": "Microsoft"
    },
    "editorUrl": "https://script-lab.azureedge.net",
    "runnerUrl": "https://script-lab-runner.azureedge.net",
    "samplesUrl": "https://raw.githubusercontent.com/OfficeDev/office-js-snippets/deploy-prod"
}
```

We don't necessarily need all of this, but the timestamp of deployment and the commit hash -- i.e., same as what the Editor shows, and what I'd like the console to show on load too -- would be nice.

**Comment by wandyezj** [comment]
Script Lab has an About page which shows the last commit, which is good enough.
