### ISSUE TITLE
Robustness: understand why #517 was happening

### ISSUE THREAD

**Issue by Zlatkovsky** [OfficeDev/script-lab#547]
Forking issue #517.

The fix to it does the concrete fix of making the "#" sign be skipped over in libraries-processing, and thus avoids the issue.

However, I think it's still important to understand why did that error firing cause the rest of the app to become completely unresponsive.  (No other actions would fire, tabs wouldn't switch, delete would show the dialog but don't do anything, etc.)

There is a general question here for robustness in the face of failure.  (And also why this failure wasn't being bubbled up to a global error-handler).

**Comment by Zlatkovsky** [comment]
To repro, just sync to any of the forks in their Jan 6 2019 or earlier state.  And follow the repro steps on #517

**Comment by wandyezj** [comment]
Obsolete.
