### ISSUE TITLE
script-lab-local*.xml is missing Spanish and Chinese localization

### ISSUE THREAD

**Issue by annich-MS** [OfficeDev/script-lab#559]
Both local manifests (WXP and Outlook) are missing Spanish and Chinese localization.

**Comment by Zlatkovsky** [comment]
Per decision in https://github.com/OfficeDev/script-lab/issues/561, we are going to keep localhost english-only (and will, in fact, remove German from that manifest).  That way there is only one file (PROD) that we have folks localize, which keeps it easier and avoids duplication.
