### ISSUE TITLE
Can be two static english strings from snippet.ts moved to the strings files for translation?

### ISSUE THREAD

**Issue by maninweb** [OfficeDev/script-lab#566]
Hi there,

while playing around and trying to import some Gists, I found that two strings are included in `src/client/app/effects/snippet.ts` which are in English and therefore not included in the strings files for translations.

The two strings are located on line 330 ` ... Cannot import a snippet created for ${rawSnippet.host} in ${environment.current.host} ...` and on line 408 `... does not support the required API Set ...`.

Would it be possible to move them to the strings files, so that they can be translated? Thanks :-)

Best,
Mourad

**Comment by Zlatkovsky** [comment]
Yes, thanks for the catch.  I'll take care of it.

**Comment by Zlatkovsky** [comment]
@maninweb, I have checked in a fix.  The strings are ready for you to translate when you are ready.

**Comment by maninweb** [comment]
Thank you :+1:
