### ISSUE TITLE
After signing in, see Gists as empty

### ISSUE THREAD

**Issue by Zlatkovsky** [OfficeDev/script-lab#570]
![image](https://user-images.githubusercontent.com/2230453/29373989-c05afbc8-8264-11e7-9ef1-3f47a526ec3e.png)

* * *

It takes a reload of the add-in to actually see the snippets.

@cshashwat, I thought you'd fixed something like this already before.  Or is your fix just not in prod yet (I was using Production Script Lab).

**Comment by cshashwat** [comment]
The fix is not in production yet, I don't have an issue in the Edge environment.
