### ISSUE TITLE
Script Lab throws debug error on load

### ISSUE THREAD

**Issue by OfficeAddins** [OfficeDev/script-lab#576]
## Description
When I open Excel and click on "Code" the task pane starts to load and when it does load I see the following Webpage Error message pop up.

![webpage-error](https://user-images.githubusercontent.com/31119149/29442581-6655ab5c-83ca-11e7-8696-a97142257ad6.png)
![samples-taskpane](https://user-images.githubusercontent.com/31119149/29442570-4edce92c-83ca-11e7-9292-7870d42cf803.png)

When I press No the Samples are displayed
(sometimes the error message is displayed more than once)
Whenever I Reload the add-in using the shortcut menu on the right hand side of the task pane, the message pops up again

## Expected Behavior
Should display the Samples without an error message

## Current Behavior
Error message appears once when I first open the Code task pane

## Possible Solution
n/a

## Steps to Reproduce (for bugs)
Open Excel
Display the 'Script Lab' tab
Click on Code

## Context
Wanting to browse the list of samples

## Your Environment
![about-screen](https://user-images.githubusercontent.com/31119149/29442825-fb818a6a-83cb-11e7-868c-91b485b63d5c.png)

Subscription/Office 365 - Excel 2016 (64 bit)
Excel 2016 - 16.0.8229.2086
Windows 10 Home, 10.0.15063 Build 15063 which is 64 bit windows

## Useful logs
I am also seeing the following error message when I open Internet Explorer
![internet-explorer-error](https://user-images.githubusercontent.com/31119149/29442874-3f46f51e-83cc-11e7-83a2-16cfe7f2df55.png)
Internet Explorer - 11.540.15063.0
Update Versions - 11.0.45

**Comment by Zlatkovsky** [comment]
@dsaunders45459 , any ideas?

Could it be that we are running code before the DOM is fully ready?  https://stackoverflow.com/questions/7173398/unable-to-get-value-of-the-property-appendchild-object-is-null-or-undefined

**Comment by OfficeAddins** [comment]
I ran a repair on Visual Studio yesterday and the error message is no longer appearing. Script Lab is opening fine and displaying the samples without any error messages. Maybe it is/was a problem with my laptop.

I am also seeing the following Navigation Error always appearing "every time" I press F5.
![image](https://user-images.githubusercontent.com/31119149/29506874-a5d9e7e8-8645-11e7-83eb-adf4fb75d348.png)

Despite going in and pressing "Go on to the webpage"
![image](https://user-images.githubusercontent.com/31119149/29506900-c37724aa-8645-11e7-8bcd-fa9633251f85.png)

I thought you only had to do this once and it would remember ?

many thanks again and sorry for what might have been a false alarm

**Comment by Zlatkovsky** [comment]
Just to clarify, are you running the "public" Script Lab (from the Office Store), or are you running from source (I.e., on localhost)?  Thanks!

**Comment by OfficeAddins** [comment]
Just the public one, from the store

**Comment by Zlatkovsky** [comment]
And do you have something like Fiddler or some other proxy server running?  Does it happen on only a particular internet network (firewall?)

I'm also quite surprised that VS would have anything to do with it.

Also, do you have another computer or virtual machine you could try on?

**Comment by OfficeAddins** [comment]
Script Lab seems to be working fine now - its a fantastic tool !

As for my other issues, It looks like it might have been related to this:
https://developercommunity.visualstudio.com/content/problem/52422/vs-2017-all-newexisting-https-web-sites-give-a-cer.html

I am installing Visual Studio 2017 15.3 and will let you know what I find, thanks again

**Comment by Zlatkovsky** [comment]
OK, great.  And I'm glad that the tool is coming in handy for you :-)
Since it sounds like a known problem with VS, let me mark it as "external".  Please let us know whether installing the latest updates fixes it for you, and then I can close this issue.

**Comment by Zlatkovsky** [comment]
(Sorry, pressed the wrong button.  Meant to comment, not close)

**Comment by OfficeAddins** [comment]
Its all working as expected. Thanks again
