### ISSUE TITLE
PowerPoint "Run" task pane shows code

### ISSUE THREAD

**Issue by AlexJerabek** [OfficeDev/script-lab#579]
### Bug Report

- **Host**: PowerPoint
- **OS**: Windows 10
- **Browser**: N/A
- **Environment**: Beta

#### Expected behavior:

The "Run" task pane shows the add-in.

#### Actual behavior:

The "Run" task pane is another "Code" task pane.

#### Steps to Reproduce:

1. Open "Code".
2. Open "Run"

#### Screenshot:

![ppt double code](https://user-images.githubusercontent.com/38896772/51359421-87e96e80-1a7c-11e9-9467-f1d849fa7063.jpg)

**Comment by Zlatkovsky** [comment]
Whoa!  That doesn't seem right.  (Neither is the fact that you have yaml in the "script" portion of the right pane -- but that's probably beside the point).

I am not able to repro it, however, running on Production.

![image](https://user-images.githubusercontent.com/2230453/51366519-ed4c5800-1a9a-11e9-8df6-f1ec0fa544db.png)

@nico-bellante , could you see if you can repro, and/or if you can inspect what's happening on Alex's machine?

**Comment by AlexJerabek** [comment]
@nico-bellante I just reproed this in Excel too.

**Comment by Zlatkovsky** [comment]
Talked with Alex.  The issue resolved itself the next day for him, and there is nothing I can think of that would have caused this.
Closing as no-repro.
