### ISSUE TITLE
TypeError: Unable to get property 'run' of undefined or null reference

### ISSUE THREAD

**Issue by kevinwirahadi** [OfficeDev/script-lab#580]
### Bug Report

- **Host**: EXCEL 2016 MSO (16.0.4266.1001) 64-bit, WORD (16.0.4266.1001)  64-bit
- **OS**: Windows 10 Enterprise 1083

#### Expected behavior:

Run/Start the out of the box sample from Script Lab such as "Basic API Call (TypeScript)" sample

#### Actual behavior:

Error Message Pop out "TypeError: Unable to get property 'run' of undefined or null reference"

#### Steps to Reproduce:

1. Install Script Lab Add-ins
2. Choose any sample Script available out of the box
3. Fail with error message "TypeError: Unable to get property 'run' of undefined or null reference"

#### Screenshot:

![image](https://user-images.githubusercontent.com/46803122/51362361-3b4e7380-1b0e-11e9-8e0c-513132e3492f.png)

edit 1: add Word as other host, the same behavior occurs in Word's Script Lab

**Comment by Zlatkovsky** [comment]
Thanks for reporting.

Just to check:  do you have the latest updates installed, from https://docs.microsoft.com/en-us/officeupdates/office-updates-msi?  The symptoms remind me a lot of an issue that we saw with someone who had an unpatched version of Office 2016...

Note to self:  if this is the case, we need to port the existing logic/fix that we made in Script Lab 2017, but that it looks like we didn't port in the new version.  The original code is at https://github.com/OfficeDev/script-lab-2017/commit/05cef2d600cac6c437732bb9e024149d06900f96.  It doesn't fix the issue, but it preempts it by prompting developers to go and install the updates as per the above.

**Comment by Zlatkovsky** [comment]
@kevinwirahadi , co-assigning to you to see if installing the updates will fix the issue (see link above)

**Comment by kevinwirahadi** [comment]
@Zlatkovsky, it worked as expected after installing "January 2, 2019, update for Office 2016 (KB4461435)" from the link given.
Thank you.
--

**Comment by Zlatkovsky** [comment]
Ok, great.  I’ll actually keep this issue open, then, to make sure we add a proper error that directs people to install the update.  Thanks for reporting and validating the workaround!

**Comment by kevinwirahadi** [comment]
No problem, glad I could help. 😄
