### ISSUE TITLE
script-lab-tutorial.xlsx link is broken. 

### ISSUE THREAD

**Issue by user135711** [OfficeDev/script-lab#591]
https://github.com/OfficeDev/script-lab/blob/master/src/client/assets/documents/script-lab-tutorial.xlsx
referenced on the main page is broken

**Comment by innovocad** [comment]
Try - https://script-lab.azureedge.net/assets/documents/script-lab-tutorial.xlsx

taken  from Excel | Script Lab Tutorial tab.

**Comment by Zlatkovsky** [comment]
Thanks for reporting.  Will be fixed shortly (have a PR open already)
