### ISSUE TITLE
[Regression] Heartbeat stops working after sharing a snippet

### ISSUE THREAD

**Issue by Zlatkovsky** [OfficeDev/script-lab#593]
Not sure what the root cause is, but it seems like a 100% repro.  Seems to be for all hosts, though I repro-ed in web, since that has easiest debugging.

1. Start with a blank snippet in the web and a runner side-by-side
https://bornholm-edge.azurewebsites.net?mode=web
https://bornholm-edge.azurewebsites.net/run.html?gallery=true&mode=web

2. Create the snippet and then click on it in the runner.

So far so good, if you change code in the editor you should see the heartbeat-refresh message in the runner. (go ahead and refresh)

3. Now share the snippet as a secret gist.

4. Make a change in the editor.  No more heartbeat.  If you refresh the runner, you'll get the external-source-trust message (https://github.com/OfficeDev/script-lab/issues/592).  But even if you do trust, the heartbeat doesn't seem to come back.

BTW, not sure when exactly regressed, but it may have been a little while ago -- not sure if prod has this issue now as well.  However, it is from something in the last few weeks, it wasn't the case before.

**Comment by WrathOfZombies** [comment]
Got this while following the repro steps:
![image](https://user-images.githubusercontent.com/3244360/29850861-6c06f8b6-8ce5-11e7-875d-b8975b80d7e9.png)

**Comment by Zlatkovsky** [comment]
@WrathOfZombies,... interesting.  And possibly as worrysome, if not more.  You're getting this in the runner page?

Does this happen to you in an in-private window as well, or just in your current cache state?  what if you blow away the localSettings but not the cache, or vice-versa?

Filing it as a separate bug might be a good idea, just to make sure it doesn't get lost here with the heartbeat one...

**Comment by WrathOfZombies** [comment]
Blowing the cache or incognito fixes the problem but I feel there's a bigger thing at play here:
![image](https://user-images.githubusercontent.com/3244360/29899458-80ea3a02-8da0-11e7-97f7-a95f1f6a54b8.png)

Looking at that image, it shows that we are trying to load the files from the runner domain and not the editor domain and that's cause of the fact that the paths begin with a `/` But I could swear that we print the `origin` before it, which means that the `origin` was set to `null` and I am not sure why that's happening.

**Comment by Zlatkovsky** [comment]
Verified that the refresh works.  Closing.  (For Bhargav's other issue, it is being tracked separately -- though we need a repro)
