### ISSUE TITLE
Script Lab does not work in Safari private window

### ISSUE THREAD

**Issue by dsaunders45459** [OfficeDev/script-lab#603]
Open private window and visit https://bornholm-edge.azurewebsites.net
Script Lab will never load even with refreshing page

These are the exceptions I get:
[Error] QuotaExceededError: DOM Exception 22: An attempt was made to add something to storage that exceeded the quota.
	switchStorage (vendor.4cd304e94b61c791faeb.bundle.js:1:375576)
	Storage (vendor.4cd304e94b61c791faeb.bundle.js:1:375222)
	Environment (main.59eb4c81ab34622b96bc.bundle.js:1:72197)
	(anonymous function) (main.59eb4c81ab34622b96bc.bundle.js:1:76186)
	__webpack_require__ (polyfills.9e546a8bf900b89b4198.bundle.js:1:124)
	(anonymous function) (main.59eb4c81ab34622b96bc.bundle.js:1:76242)
	__webpack_require__ (polyfills.9e546a8bf900b89b4198.bundle.js:1:124)
	(anonymous function) (main.59eb4c81ab34622b96bc.bundle.js:1:173174)
	__webpack_require__ (polyfills.9e546a8bf900b89b4198.bundle.js:1:124)
	(anonymous function) (main.59eb4c81ab34622b96bc.bundle.js:1:63530)
	__webpack_require__ (polyfills.9e546a8bf900b89b4198.bundle.js:1:124)
	(anonymous function) (main.59eb4c81ab34622b96bc.bundle.js:1:504114)
	__webpack_require__ (polyfills.9e546a8bf900b89b4198.bundle.js:1:124)
	(anonymous function) (main.59eb4c81ab34622b96bc.bundle.js:1:221602)
	__webpack_require__ (polyfills.9e546a8bf900b89b4198.bundle.js:1:124)
	(anonymous function) (main.59eb4c81ab34622b96bc.bundle.js:1:695643)
	__webpack_require__ (polyfills.9e546a8bf900b89b4198.bundle.js:1:124)
	webpackJsonp (polyfills.9e546a8bf900b89b4198.bundle.js:1:474)
	global code (main.59eb4c81ab34622b96bc.bundle.js:1)
[Error] TypeError: n.i(i.v) is not a function. (In 'n.i(i.v)("ribbon")', 'n.i(i.v)' is undefined)
	(anonymous function) (indexScript.11956fa0a40a6f749069.bundle.js:1:144383)
	(anonymous function) (indexScript.11956fa0a40a6f749069.bundle.js:1:144895)
	__webpack_require__ (polyfills.9e546a8bf900b89b4198.bundle.js:1:124)
	webpackJsonp (polyfills.9e546a8bf900b89b4198.bundle.js:1:474)
	global code (indexScript.11956fa0a40a6f749069.bundle.js:1)
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):

## Useful logs

- [ ] Fiddler traces
- [ ] Console errors
- [ ] Screenshots
- [ ] Clip or GIFs

**Comment by Zlatkovsky** [comment]
This is by design.  localStorage on Safari in-private is not supported.  And as such, neither is Script Lab.

https://stackoverflow.com/questions/14555347/html5-localstorage-error-with-safari-quota-exceeded-err-dom-exception-22-an

If today's experience isn't good UX-wise, please post a picture and/or suggest a fix.
