### ISSUE TITLE
Getting a "permission denied" error when running snippet in the Code pane in Excel Online

### ISSUE THREAD

**Issue by jakobpn** [OfficeDev/script-lab#607]
![image](https://user-images.githubusercontent.com/13109307/30190435-f3faae7e-93ee-11e7-8f45-b5b9614fcb5b.png)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):

## Useful logs

- [ ] Fiddler traces
- [ ] Console errors
- [ ] Screenshots
- [ ] Clip or GIFs

**Comment by Zlatkovsky** [comment]
Seems like a regression...

**Comment by Zlatkovsky** [comment]
This was an issue (regression) that I introduced last week, but I believe that it's now fixed.  If not, please re-open.
