### ISSUE TITLE
Renaming the Settings sample for Excel

### ISSUE THREAD

**Issue by maninweb** [OfficeDev/script-lab#616]
Hi there,

when I try to save my script as _Settings,_ then (1) is automatically appended to the name. I guess, this is due to that Script Lab already uses this filename for its own user/default settings.

Let's assume, I am a new user to Script Lab, who freshly installed the app and is trying out the samples for **Excel**. All samples which are opened get the same filename as the sample name. Excepted one: the sample for _Settings_ from the _Documents_ category, where the appending of (1) is then done too. I think, that could be irritating for some users. Also because trying to rename it to _Settings_ in the Save dialog leads to that the filename is not changed.

My suggestion would be to rename the _Settings_ Sample from the Script Lab Samples to e.g. _Document Settings_. Then, that sample will act like all other samples and have its filename set to its sample name.

Best,
Mourad

**Comment by Zlatkovsky** [comment]
Mourad, that's a great bug! :-)

I'm co-assigning two people to it:
- @AlexJerabek , could you do the quick tactical fix of renaming the Settings sample to "Document Settings", per Mourad's suggestion?
- @nico-bellante , we should not be hardcoding the word Settings (or if we must, it better be something like `_#SeTt!ngs_!` to make it impossible to conflict with any sane user-generated name).  Could you fix it when you do your next refactor?

**Comment by nico-bellante** [comment]
@Zlatkovsky sure thing.

@maninweb, thanks for finding this issue! I completely overlooked this case when implementing the functionality that ensures a unique name for a snippet.

**Comment by AlexJerabek** [comment]
The [snippet PR](https://github.com/OfficeDev/office-js-snippets/pull/261) is ready for review.

**Comment by maninweb** [comment]
Hi all - thanks :-)
