### ISSUE TITLE
Multiple issues with title bar

### ISSUE THREAD

**Issue by saunders77** [OfficeDev/script-lab#62]
•	When you click the pancake button in Script view, the other icons move to the left before the fade animation
•	All of the buttons have tooltips except the pancake and the Info button
•	The expanding-logic (when you switch to strings) is inconsistent: the Title seems to expand at around 400px, but for some reason you have to go all the way to like 800px in order to see the other strings
•	The Info icon disappears during expansion, whereas all the other buttons keep their icons during expansion

**Comment by Zlatkovsky** [comment]
This bug is quite old, and I know that Bhargav had one some work here. Can you check what, if any, is still relevant here?

**Comment by Zlatkovsky** [comment]
Closing as something old that hasn't been re-validated for some time.  If we still have an issue, we should open it as a new one.
