### ISSUE TITLE
add-in error 

### ISSUE THREAD

**Issue by sxwild** [OfficeDev/script-lab#621]
When trying to run the demo 'Basic API call' I get an error -> "add-in error"
## Expected Behavior

Expecting to be able to select some cells in Excel and for them to be shaded yellow.

## Current Behavior

After selecting run get a warning symbol and on clicking on that get the following screen:

![image](https://user-images.githubusercontent.com/32048613/30527563-baa8b1a2-9c6d-11e7-9699-808263dacf9a.png)

## Steps to Reproduce (for bugs)

1. Select demo 'Basic API call'
2. Run demo
3. Get warning symbol in script-lab console
4. Click on warning and get message "add-in error"

## Context

I can't run a demo of script-lab

## Your Environment

* Version used: 1.1.0
* Operating System and version (desktop or mobile): mac OS 10.12
* Excel: 15.30

**Comment by Zlatkovsky** [comment]
Thanks for reporting the issue.  @jakobpn, since you also have a mac, could you follow up with @sxwild and see if you can narrow down the issue? @

**Comment by jakobpn** [comment]
Hi @sxwild, I tested this on my Mac which runs a newer build of Excel than you. I wondering if you can try updating Excel to a more recent build (for example, 15.37 that was released in July) and let us know if you still experience the issue with the basic snippet.

**Comment by sxwild** [comment]
Hi @jakobpn, I have upgraded to Excel 15.38 and that has fixed it.

Thanks
