### ISSUE TITLE
Pasting in a blob of JSON with a comma at the end causes editor to throw error screen

### ISSUE THREAD

**Issue by Zlatkovsky** [OfficeDev/script-lab#623]
Repro:

1. In a new snippet, type: `console.log()`
2. Between the parentheses, type `{a: 6},`, **with the comma included**
3. Observe that nothing happens.  Now select this text and copy it to clipboard.
4. Now paste it.  This time, you'll get an error screen!

![image](https://user-images.githubusercontent.com/2230453/52830588-3a195380-3086-11e9-9651-b84f64551082.png)

**Comment by nico-bellante** [comment]
Hmmm this sounds like a fun one to debug. For starters, which platform did it occur on?

Couple ideas off the top of my head:
1. I believe there is some sort of setting that is like formatOnPaste or something of that nature for monaco which then invokes prettier... Perhaps that could be throwing this error. One way to test would be to just disable prettier in the settings.
2. It could be a TypeScript issue. Just found [this](https://github.com/Microsoft/TypeScript/issues/24577) which is getting a similar error message. What did the rest of the code look like? Did it repro with just the console.log() line?
3. Less likely as I just tried to repro on monaco playground and failed, but it could potentially be a hard to catch monaco bug.
