### ISSUE TITLE
Ensure we're doing the right thing with snippet trusting for Custom Functions

### ISSUE THREAD

**Issue by Zlatkovsky** [OfficeDev/script-lab#625]
Just noticed we have the following commented out:

```
      // TODO:  why do we have code commented out?
      // const isTrusted = trustedSnippetManager.isSnippetTrusted(snippet.id, snippet.gist, snippet.gistOwnerId);
      // let status;
      // if (isTrusted) {
      const status: CustomFunctionsRegistrationStatus = hasErrors ? 'error' : 'good';
      // } else {
      //     status = CustomFunctionsRegistrationStatus.Untrusted;
      // }
```

We should make sure we're doing the right thing with trusted snippets (or just ignoring untrusted ones)

**Comment by Zlatkovsky** [comment]
Note: somewhat related to https://github.com/OfficeDev/script-lab/issues/466, will be touching that code anyway at that point.

**Comment by Zlatkovsky** [comment]
FWIW, looks like we're already filtering them out earlier at
`.filter((solution: ISolution) => !solution.options.isUntrusted)`
So this code might just be removable.

**Comment by nico-bellante** [comment]
I can't fully remember why that code wasn't removed. If I were to guess, I'd say it was because of `status` for some reason or another. Probably save to remove.

**Comment by Zlatkovsky** [comment]
Resolved within the `zlatkovsky/cf-metadata` branch.
