### ISSUE TITLE
Console getting cut off

### ISSUE THREAD

**Issue by Zlatkovsky** [OfficeDev/script-lab#628]
If have long text (e.g., in error stack), the console output is getting cut off!

![image](https://user-images.githubusercontent.com/2230453/52892627-04896e80-3149-11e9-905d-6c1456cb18c6.png)

**Comment by nico-bellante** [comment]
What is the desired behavior?

**Comment by nico-bellante** [comment]
The horizontal scroll could feel awkward... wrapping could look ugly..
