### ISSUE TITLE
FileSwitcherPivot.test.tsx says it passes, though it also shows console error

### ISSUE THREAD

**Issue by Zlatkovsky** [OfficeDev/script-lab#640]
When running `yarn workspace editor test`, it reports success, even though there is also a `console.error` that happens!

So the issues are:
1. Failures shouldn't be reported as success!
2. The failure itself should be fixed.

@nico-bellante , could you please take a look?

```
 PASS  src/pages/Editor/components/Main/FileSwitcherPivot/FileSwitcherPivot.test.tsx (16.406s)

  ● Console

    console.error ../../node_modules/redux/lib/redux.js:313
      Unexpected keys "profilePicUrl", "username", "token" found in preloadedState argument passed to createStore. Expected to find one of the known reducer keys instead: "loginInfo", "isLoggingInOrOut", "isAuthDialogVisible". Unexpected keys will be ignored.
    console.group src/pages/Editor/store/configureStore.ts:25
        EDITOR_OPEN_FILE
    console.log src/pages/Editor/store/c
```

**Comment by Zlatkovsky** [comment]
Note: putting it on the "backburner", but realistically it'd be good to get it fixed soon.  Tests that say that pass even when they fail aren't a good thing -- and neither is the noise in the console.

**Comment by nico-bellante** [comment]
it has console errors because when you did the github reducer change the state specified on line 114 in that file was not changed to match.

it passes because I'm guessing it doesn't care too much and the part it cares about still works.
