### ISSUE TITLE
Import button is rendered at the top of the dialog instead of at the bottom

### ISSUE THREAD

**Issue by jakobpn** [OfficeDev/script-lab#644]
![image](https://user-images.githubusercontent.com/13109307/30769723-dbddffd0-9fd3-11e7-9243-ac1e65775bdb.png)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: Beta
* Browser Name and version: Safari
* Operating System and version (desktop or mobile): Mac in Excel Desktop

## Useful logs

- [ ] Fiddler traces
- [ ] Console errors
- [ ] Screenshots
- [ ] Clip or GIFs

**Comment by Zlatkovsky** [comment]
Renders fine on PC...  Will need to investigate on a Mac.
What about going to that same screen on https://bornholm-insiders.azurewebsites.net?  Both on Mac and Chrome?

**Comment by jakobpn** [comment]
It render better outside of the client although at a smaller size the button moves into the text box.

![image](https://user-images.githubusercontent.com/13109307/30769790-08a6505c-9fd5-11e7-9ef0-8457f9087fc1.png)

**Comment by Zlatkovsky** [comment]
The overlay surprises me less (and is arguably OK).  The non-working state on the Mac is... less OK.  Though not 100% sure what I can do about it.
