### ISSUE TITLE
Exception thrown when trying to add CSS or HTML by using IntelliSense

### ISSUE THREAD

**Issue by maninweb** [OfficeDev/script-lab#648]
Hi there,

I noticed that I can produce an exception when editing an already existing style and using the IntelliSense dropdown. Please note, that's possible you have to try several times, before you see the following error. I could reproduce it best, if I start with a new snippet or a saved new snippet. I am using Excel 1902 Build 11328.20116 and ScriptLab as shown below.

![image](https://user-images.githubusercontent.com/13045898/53679391-842c4700-3ccc-11e9-85de-c3445f0c06f7.png)

Please create a new snippet and then navigate to the CSS tab. There are already some defined styles there. Press Enter after the first style for the margins and type the character _m_. It looks then like the following screenshot.

![image](https://user-images.githubusercontent.com/13045898/53679468-4c71cf00-3ccd-11e9-9927-d02599d111ce.png)

From the list, click for example on `margin-block-start`. Script Lab immediately throws an unexpected error message.

![image](https://user-images.githubusercontent.com/13045898/53679510-a377a400-3ccd-11e9-983b-7e6b13726f1d.png)

If I click on the button for more info, this is shown ...

> Invalid start index: 2
> Error: Invalid start index: 2
>    at e.prototype.splice (https://script-lab.azureedge.net/external/monaco-editor-0-14-3/vs/editor/editor.main.js:722:447)
>    at Anonymous function (https://script-lab.azureedge.net/external/monaco-editor-0-14-3/vs/editor/editor.main.js:1687:160)
>    at o (https://script-lab.azureedge.net/static/js/2.fb57e2f5.chunk.js:1:3080290)
>    at Anonymous function (https://script-lab.azureedge.net/static/js/2.fb57e2f5.chunk.js:1:3080437)
>    at u (https://script-lab.azureedge.net/static/js/2.fb57e2f5.chunk.js:1:364063)

Once I have closed the error message, I reach the editor again, where the selected style has been inserted.

![image](https://user-images.githubusercontent.com/13045898/53679608-eab26480-3cce-11e9-8e05-e2ebcab960e5.png)

I can continue to type and edit then, e.g. set the px's. And, adding new lines works, also if I select styles from the dropdown. So, it seems to be an issue only when I start the Code Pane.

I tried to reproduce the error message from the Script and HTML tabs. I could not for the Script tab, but from the HTML tab. What I also noticed is that it perhaps depends on how many chars I enter before I select an item from the IntelliSense dropdown.

Best,
Mourad

**Comment by Zlatkovsky** [comment]
@maninweb , thanks for reporting.  It feels similar to another issue I discovered recently, https://github.com/OfficeDev/script-lab/issues/623.

My hope is that an update to the Monaco editor, which I'll be doing in the next couple of weeks anyway, will automatgically fix this.  If not, we'll need to investigate...
