### ISSUE TITLE
Cypress doesn't seem to work anymore

### ISSUE THREAD

**Issue by Zlatkovsky** [OfficeDev/script-lab#659]
At least on my laptop, it no longer opens the side-by-side page with the cypress runs, like it used to

Instead, it just displays Script Lab normally:

![image](https://user-images.githubusercontent.com/2230453/53906790-a1c91b80-4000-11e9-8da7-680b82d8d282.png)

Is our routing somehow getting in the way of Cypress?

**Comment by wandyezj** [comment]
Obsolete. Cypress is not used in a meaningful way to test.
