### ISSUE TITLE
Outputting a sufficiently large string to the console makes SL unresponsive

### ISSUE THREAD

**Issue by AlexJerabek** [OfficeDev/script-lab#665]
### Bug Report

- **Host**: Excel
- **OS**: Windows
- **Browser**: Win32
- **Environment**: Beta

#### Expected behavior:

The string goes to the console and SL acts normally.

#### Actual behavior:

![Capture](https://user-images.githubusercontent.com/38896772/54144494-13caa780-43e9-11e9-9c99-caa2d5c91e12.PNG)

#### Steps to Reproduce:

1. [Open this gist](https://gist.github.com/AlexJerabek/2837745c5af39278cf47703d99835d98)
2. Press "Create table"
3. Press "Create a doughnut chart"
4. Press "output"
5. Try scrolling through the console for more than a second.

**Comment by nico-bellante** [comment]
Is it 1 particularly large string, or a large volume of small strings?

**Comment by Zlatkovsky** [comment]
@AlexJerabek , this does not repro for me (at least on my beefy desktop machine).  The console output is perfectly happy.

Even if it did, though, it's really more of a platform issue than a Script Lab issue (unless SL was doing something horrendously bad performance-wise, like getting stuck in an infinite loop).  So I suggest you bring it up to AlexCro or Robert.  I believe @jakobpn has also occasionally run into similar issues.

Closing this bug as external, as there is nothing I can do about it.
