### ISSUE TITLE
Run pane not detecting Code pane

### ISSUE THREAD

**Issue by AlexJerabek** [OfficeDev/script-lab#674]
### Bug Report

- **Host**: Excel
- **OS**: Windows
- **Browser**: Win32
- **Environment**: Beta

#### Expected behavior:

Run pane shows the snippet's UI.

#### Actual behavior:

Run pane Says "No snippet to run", even after hard refreshing.

#### Steps to Reproduce:

1. Open SL Code and Run

#### Screenshot:

![image](https://user-images.githubusercontent.com/38896772/54551603-a4fec880-496b-11e9-94e8-cfce31073f75.png)

**Comment by Zlatkovsky** [comment]
If you close and reopen both panes, does it fix it?

**Comment by AlexJerabek** [comment]
@Zlatkovsky Negative. Closing and reopening Excel doesn't help either.

**Comment by Zlatkovsky** [comment]
If it still doesn't help, I can debug with you in a couple hours

**Comment by Zlatkovsky** [comment]
@AlexJerabek , I believe it should now be fixed.  Just tried it myself and I can no longer repro what I could before.  Please try again and reopen if anything is still amiss.
