### ISSUE TITLE
Position of the editor context menu lets sometimes be entries not visible

### ISSUE THREAD

**Issue by maninweb** [OfficeDev/script-lab#697]
Hi there,
I noticed, that sometimes the upper entries from the context menu are not visible. This is due to that if you right click at certain positions in the editor, the context menu is placed above the position where the right click occured. I added some screenshots below to visualize the problem.

![image](https://user-images.githubusercontent.com/13045898/54882533-4a79d680-4e5b-11e9-9e96-6ff28c5b5154.png)
![image](https://user-images.githubusercontent.com/13045898/54882555-74cb9400-4e5b-11e9-8831-648af003c74a.png)
![image](https://user-images.githubusercontent.com/13045898/54882580-b8be9900-4e5b-11e9-9842-2edf79f260fe.png)
![image](https://user-images.githubusercontent.com/13045898/54882594-e73c7400-4e5b-11e9-8214-3fcb89f558ac.png)

For seeing the effect with the invisible menu entries, it may be possible, that you have to resize the Excel window. In maximized state of the Excel window on a large monitor, I could not reproduce the issue. In my tests above, my Excel window had a size about 1300 * 1000.
I guess, that the issue has perhaps something to do with the space available between the last line and the bottom edge of the editor.

Best,
Mourad

**Comment by nico-bellante** [comment]
We could probably move the z-index of the editor to be on top, but then I believe we will have issues with the message bar animations.

**Comment by wandyezj** [comment]
This seems to be fixed with the monaco update.
