### ISSUE TITLE
when i click center textbox,it's throw error

### ISSUE THREAD

**Issue by dinglicoding** [OfficeDev/script-lab#700]
hi
i use the script-lab for excel, i click the demo of textbox.it's error for createGeometricShape and centerTextbox method
my excel is office home and student 2016  version 1902 ( build 11328.20154 )
![image](https://user-images.githubusercontent.com/3963826/55124623-d2a0fa00-5141-11e9-9fe5-2cb0b1520669.png)

**Comment by nico-bellante** [comment]
Hmm.. perhaps shapes aren't supported in that version of Excel. @AlexJerabek do you happen to know?

**Comment by AlexJerabek** [comment]
@dinglicoding The Shape APIs recently underwent some changes. You might be on a slightly older version than the sample requires. I just successfully ran it using 1904. Are the other preview samples working?

(Also, @nico-bellante, I don't think this is a Script Lab problem. Feel free to transfer the issue to office-js-snippets).

**Comment by nico-bellante** [comment]
@AlexJerabek the only part that I think might be a SL problem is the fact that it showed a sample that couldn't be run. I don't believe the samples even go through an api_set check, and that sounds like something they probably should...  Would that have caught this issue?

**Comment by AlexJerabek** [comment]
@nico-bellante  API sets aren't that granular. Both versions of the Shape APIs are in the Preview API set. Needing to delineate those distinctions isn't necessary outside of preview stuff, so I think it's okay to say they're only compatible with the latest version.

Of course, if they're not working, I'll still gladly welcome issues of the snippets repo. It's a challenge to keep the samples and APIs in sync, so any user input into that helps.

**Comment by nico-bellante** [comment]
Cool, thanks for clarifying.
