### ISSUE TITLE
In add-ins list, says "ScriptLab" instead of "Script Lab"

### ISSUE THREAD

**Issue by ElizabethSamuel-MSFT** [OfficeDev/script-lab#705]
### Bug Report

- **Host**: OUTLOOK
- **OS**: Windows
- **Browser**: 
- **Environment**: alpha

#### Expected behavior:

Should say "Script Lab"

#### Actual behavior:

Says "Script"

#### Steps to Reproduce:

1. See screen shot

#### Screenshot:

![image](https://user-images.githubusercontent.com/28541963/55261485-58977080-5228-11e9-91ed-aa4aea59e67d.png)

**Comment by ElizabethSamuel-MSFT** [comment]
Updated manifest so new screenshot:
![image](https://user-images.githubusercontent.com/28541963/55262834-58996f80-522c-11e9-939a-6919b586c8ea.png)

**Comment by nico-bellante** [comment]
Likely came from https://github.com/OfficeDev/script-lab/pull/703

**Comment by Zlatkovsky** [comment]
@ElizabethSamuel-MSFT , @annich-MS , feel free to submit a PR to fix this.
