### ISSUE TITLE
Uppercasing a Custom Function causes "duplicate function name" error

### ISSUE THREAD

**Issue by davidchesnut** [OfficeDev/script-lab#709]
Try renaming "add10" to ADD10, and you'll get an error:

```
/** @CustomFunction */
function ADD10(x: number): number {
  return x + 10;
}
```

`@customfunction tag specifies a duplicate name: ADD10 (1,1)`

**Comment by Zlatkovsky** [comment]
After investigating it, I see that the issue is with the "custom-functions-metadata" parser, not Script Lab.  Opened an issue on that repo.  Marking this one as blocked.

I added a test (now failing) at https://github.com/OfficeDev/script-lab/tree/fix-709

**Comment by Zlatkovsky** [comment]
Fix pending as part of https://github.com/OfficeDev/script-lab/pull/719

**Comment by akrantz** [comment]
@Zlatkovsky Has the fix for this bug now been released?

**Comment by Zlatkovsky** [comment]
Has now.  I needed to push it master => beta => prod and to clear the CDN cache.
It's in production now.  Closing.
