### ISSUE TITLE
Reference docs / Helps / Ask Community never appears

### ISSUE THREAD

**Issue by GrandSchtroumpf** [OfficeDev/script-lab#734]
### Bug Report

- **Host**: POWERPOINT
- **OS**: Windows10
- **Environment**: prod

#### Expected behavior:
When clicking on "Reference Docs"  or "Helps" or "Ask Community" it should show the content.

#### Actual behavior:
It's stuck on loading.

#### Steps to Reproduce:
Click on "Reference Docs" in the header

#### Screenshot:
![image](https://user-images.githubusercontent.com/8143464/57312994-f36c5000-70ee-11e9-882b-e7692269da98.png)

**Comment by GrandSchtroumpf** [comment]
In the meanwhile, where can I find the latest doc of how to build an addin for powerpoint?

**Comment by Zlatkovsky** [comment]
@GrandSchtroumpf , thanks for reporting the issue.  I will investigate.

In the meantime, the Docs URLs for all of the host applications are listed at https://github.com/OfficeDev/script-lab/blob/master/packages/common/src/safe.external.urls.ts

**Comment by Zlatkovsky** [comment]
Fixed.  Should deploy to production tomorrow.
