### ISSUE TITLE
Scriptlab routing does not affect devicePixelRatio

### ISSUE THREAD

**Issue by alx-andru** [OfficeDev/script-lab#740]
Hi, 
I came across an issue of a shrinking user interface after each navigation route change. Looking at script-lab and the sources I'm not able to find any significant change that would prevent the shrink behaviour. Is this an issue you're aware of and provided a work-around which is not quite obvious?

https://github.com/OfficeDev/office-js/issues/40

**Comment by Zlatkovsky** [comment]
Good question.  But no, there is nothing special that we did in ScriptLab.  It might be a fortuitous combination of how we weaved the components together -- but we didn't do any explicit work for this, so far as I know.

@WrathOfZombies , do you have any insights?

In the meantime, I re-pinged someone on my team, to see if we can get a status update.

**Comment by Zlatkovsky** [comment]
Underlying https://github.com/OfficeDev/office-js/issues/40 is now resolved.  Closing.
