### ISSUE TITLE
Angular 4 Code 

### ISSUE THREAD

**Issue by niteshsinghn2** [OfficeDev/script-lab#749]
Dear All,
Can anybody suggest me why this code showing  Cannot read property 'notify' of undefined inside Angular4 ajax call.
 try {
              Excel.run(async (context) =>  {
              await OfficeHelpers.ExcelUtilities.forceCreateSheet(context.workbook, "Sample");
              const sheet: any = context.workbook.worksheets.getItem("Sample");
              let expensesTable: any = sheet.tables.add("A1:C1", true);
              expensesTable.name = "ExpensesTable";
              expensesTable.getHeaderRowRange().values = [getHeader()];;
			  
              expensesTable.rows.add(null, getPreppedData());

              if (Office.context.requirements.isSetSupported("ExcelApi", 1.2)) {
                sheet.getUsedRange().format.autofitColumns();
                sheet.getUsedRange().format.autofitRows();
              }
               sheet.activate();
               await context.sync();
            });
         } catch (error) {
           OfficeHelpers.UI.notify(error);
            OfficeHelpers.Utilities.log(error);
          }
		},error => {
		   console.log("Failed to connect server");
         });

Thank You

**Comment by Zlatkovsky** [comment]
This sounds like a general office.js question, not anything specific to script lab.   I'll go ahead and close it here.  But I encourage you to post it on StackOverflow, tagged with `[office-js]`
