### ISSUE TITLE
add CODEOWNERS file

### ISSUE THREAD

**Issue by akrantz** [OfficeDev/script-lab#749]
If you add a file .github/CODEOWNERS. pull requests will automatically be assigned.

The contents would be `* OfficeDev\ScriptLab` where ScriptLab is a GitHub team.

You can see how this was done for Office-Addin-Scripts:
https://github.com/OfficeDev/Office-Addin-Scripts/blob/fc8907d1c7bd17cdf77df0d9860fc8e439174cfc/.github/CODEOWNERS#L1

**Comment by wandyezj** [comment]
Great suggestion. This has been added: https://github.com/OfficeDev/script-lab/blob/master/.github/CODEOWNERS
