### ISSUE TITLE
Script lab Issue

### ISSUE THREAD

**Issue by niteshsinghn2** [OfficeDev/script-lab#750]
Hello All,

While loading the script lab showing

A Runtime error occurred while loading the snippet

Please return to the script editor to fix the error.

Script error

**Comment by Zlatkovsky** [comment]
Could you include a screenshot / more info?  Also, what host and platform are you seeing this on?

**Comment by niteshsinghn2** [comment]
![screenshot 5](https://user-images.githubusercontent.com/20719583/36578785-74137ac6-1885-11e8-8a48-1b0949521bc6.png)

**Comment by Zlatkovsky** [comment]
Ok.  What is the snippet code, and the host/platform.  What version number?

**Comment by Zlatkovsky** [comment]
No response re. code snippet and host/platform/version.  Closing.
