### ISSUE TITLE
Facilitate debugging of this add-in in Visual Studio

### ISSUE THREAD

**Issue by robinchesterman** [OfficeDev/script-lab#751]
This add-in is not only useful to experiment with the Office JavaScript API, but is also itself a good reference implementation for architecting and bootstrapping a non-trivial Office web add-in with React, TypeScript and other frontend tools.

One of the biggest challenges I've found developing my own add-in is setting up a good TypeScript debugging experience in Visual Studio when running inside (for example) Word. It is my understanding that because Word is using IE behind the scenes, Visual Studio is the only option for this. I can't attach a VS Code debugger.

In particular, the IE / VS combination leads to dirty breakpoints when the application is bundled using webpack (as is common with React) - breakpoints that spread across multiple lines and behave in peculiar ways.

It would be very interesting to see how the script-lab team would approach this, OR get a better understanding of how / why debugging inside a true add-in environment has not been considered necessary or important.

**Comment by wandyezj** [comment]
Add-Ins are simply websites and standard website JavaScript debugging techniques with F12 browser tools apply. 

You can create and host your own Add-In on GitHub, for example see the [Build Add-In](https://github.com/wandyezj/website-react-extension) you can sideload the [manifest](https://github.com/wandyezj/website-react-extension/blob/main/manifests/production.xml).
