### ISSUE TITLE
Office-js as angular service instead of declare const Office variable

### ISSUE THREAD

**Issue by robertpmansion** [OfficeDev/script-lab#751]
What would be the best approach to inject Office-js as an angular service instead of declaring the Office variable in the main.ts as something like: `declare const Office: any;` as this is hard to test.

What I did is something like when using the `window.Office` as a service:

```
import { Injectable } from '@angular/core';

@Injectable()
export class OfficeService {

    constructor() {
        if (Office === undefined) {
            throw new Error('Office object is not available.');
        }
    }
    //...
}
```
So is there a proper way to do this and would be easier also to test?

**Comment by Zlatkovsky** [comment]
This looks like a general Office.js question, not something to do with Script Lab (Script Lab doesn't support "import" statements, among other things).
I'd recommend asking the question on <https://stackoverflow.com/tags/office-js>, and then going from there (likely resulting in an issue on https://github.com/OfficeDev/office-js/issues, but I think that going via StackOverflow is better first).

**Comment by robertpmansion** [comment]
@Zlatkovsky I did ask this via StackOverflow. I think I will just go to the next option the: https://github.com/OfficeDev/office-js/issues
