### ISSUE TITLE
Script lab not loading, crashing and not able to register functions

### ISSUE THREAD

**Issue by vishwesh17** [OfficeDev/script-lab#756]
### Bug Report

- **Host**: (EXCEL,)
- **OS**: (Windows)
- **Browser**: (Internet explorer/Chrome)
- **Environment**: (office 365, version 1908, build 11911.20000, )

#### Expected behavior:

Should be able to register as many functions I need

#### Actual behavior:

In the office insider also I was not able to register more than one function so I moved to monthly channel, but in that also facing difficulties from yesterday. I was only able to register 5 functions and from today again only 1 function and if I register 2nd function the 1st function gets obsolete in monthly channel with above version and build
Also facing issues in loading interface of script lab and crashing too in between

#### Steps to Reproduce:

1. Restart computer
2. deleted script lab add ins and again installed
3. still not able to register more than one function and crashes when I hit "Register or Run" or see "console"
4. sometimes interface keeps on loading with moving dots.

#### Failure Logs:

No error is displayed. even after doing above steps the problem remains the same

#### Screenshot:

![script lab blank](https://user-images.githubusercontent.com/53311552/62739042-d6069500-ba01-11e9-8cdf-b0b8c855aabb.png)
![Scriptlab (2)](https://user-images.githubusercontent.com/53311552/62740194-1ddaeb80-ba05-11e9-8b23-ba7703102f68.jpg)

**Comment by vishwesh17** [comment]
If I have to register the new function then I have to type it on top or else it registers the first function only.

**Comment by Zlatkovsky** [comment]
The issue is that you're not including the `/** @customfunction */` comment at the top of each function.  This comment is necessary to let Script Lab (and also the "yo-office" generator, once you're ready to do a real project) know that it's a top-level function that you want to register, rather than a helper function.

**Comment by Zlatkovsky** [comment]
As for the crashing issue:  could you describe a little more (maybe in a separate issue) how exactly you get into the crashing / blank-page state?

**Comment by vishwesh17** [comment]
Thanks for the prompt reply and guiding me in a proper direction.
