### ISSUE TITLE
Script lab crashing

### ISSUE THREAD

**Issue by vishwesh17** [OfficeDev/script-lab#757]
### Bug Report

- **Host**: (Excel)
- **OS**: (Windows)
- **Browser**: (Internet explorer/Chrome)
- **Environment**: (office 365, version 1908, build 11911.20000)

#### Actual behavior:

sometimes crashing in between when clicked on "register/run" or "console". Also the interface keeps on loading. 
Also I would like to know why I am seeing **"preview"** when I register the function, screen shoot attached

#### Steps to Reproduce:

alt+ctrl+delete to close excel, if normal closing of window does not work 
Restart Excel

Also can you guide me on my question:
https://stackoverflow.com/questions/57464480/how-get-all-details-of-api-in-in-excel-screencells-without-indexing-in-office

#### Screenshot:

![script lab blank](https://user-images.githubusercontent.com/53311552/62877037-3ba19c80-bcf4-11e9-894d-ae873d7d7cba.png)
![script lab error](https://user-images.githubusercontent.com/53311552/62877062-478d5e80-bcf4-11e9-906b-b942ddeb32bd.png)
![scriptlab error](https://user-images.githubusercontent.com/53311552/62877106-5b38c500-bcf4-11e9-8adb-6bce2138c369.png)
![Untitled](https://user-images.githubusercontent.com/53311552/62888156-b8d90b80-bd0c-11e9-9feb-3007de29421a.png)

**Comment by nico-bellante** [comment]
@akrantz @Zlatkovsky

**Comment by vishwesh17** [comment]
Also I am facing issues of freezing window(not able to scroll or navigate in script lab, ribbons and other menu not responding, no able to select cell in excel). need to forcefully close the Excel window. Is it because I register all functions in single snippet?

**Comment by Zlatkovsky** [comment]
@vishwesh17 , for the crashing (by which I assume you mean the "An unexpected error has occured" and/or the blank window):  is it happening with particular snippets?  If so, can you send me the code you use?  I need to be able to repro it locally in order to diagnose it.

Re. the "(Preview)", I think that was just an oversight (from when Custom Functions were still in preview).  I'll remove it.

Re. issues of freezing:  I don't think it has anything to do with functions being in one snippet vs. multiple.  It does seem to be a potential platform bug/instability.  If you have more concrete repro steps for when it happens, I can try to pass it on to someone to investigate.

**Comment by vishwesh17** [comment]
@Zlatkovsky , Thanks for the reply. 
I am facing crashing issues quite often from past one week, 
Excel online: build 16.0.12010.35902
functions are not active in cell even after registration ("=scr")  nothing displays in cell
![excel online error 15th august](https://user-images.githubusercontent.com/53311552/63120575-892a3d80-bf70-11e9-9d0f-0de11a0f0fcc.png)
![functions not showing after registration](https://user-images.githubusercontent.com/53311552/63121126-b62b2000-bf71-11e9-8c3e-e064cab51df6.png)

Excel desktop: Updated today morning version 1908 (build 11929.20114)
compile error is seeing for the functions 
![15th august](https://user-images.githubusercontent.com/53311552/63121459-7b75b780-bf72-11e9-8fb3-f7eb1787484a.png)

Freezing issue is seen in all snippets and not samples. following is the link to the gist I am working on.
https://gist.github.com/vishwesh17/0e0abe24c806bd727ab4fb1519740be5

Also if you can solve my problem. In the above Github gist there is a function called "trialworking". I am able to get all the details(not in proper format) but I don't know how to display "name and symbol" or other column (specific column or header) in excel with proper format from url.

Also can you share an example of "excel.run inside custom function"

**Comment by vishwesh17** [comment]
@Zlatkovsky @nico-bellante @akrantz 
When I register a function in excel online I receive this error message, screenshot attached
![script online error text](https://user-images.githubusercontent.com/53311552/63532196-1cff8a80-c4d8-11e9-864f-c84d33e6f4e0.png)

**Comment by wandyezj** [comment]
Closing stale issue.
