### ISSUE TITLE
Reference Docs ribbon button goes to page not found

### ISSUE THREAD

**Issue by hodlhodl** [OfficeDev/script-lab#758]
When I click the ribbon button “Reference Docs” a new window opens and it takes me to “We’re sorry, we can’t find the page you requested.” page on docs.

## Expected Behavior

I would expect it to take me to the API reference documentation page.

## Current Behavior

Page is not found.

## Possible Solution

1. Click ribbon button “Reference Docs"
2.
3.
4.

## Context

* Version used: 1.1.0
* Browser Name and version:
* Operating System and version (desktop or mobile): Mac Excel Desktop Version 16.12 (180314)

## Useful logs

- [ ] Fiddler traces
- [ ] Console errors
- [ ] Screenshots
- [ ] Clip or GIFs

**Comment by kbrandl** [comment]
@hodlhodl thank you for reporting this issue. Another issue was recently opened to describe issues with ribbon buttons in Script Lab, so I'm going to close this one as a duplicate (of #743). In the meantime, this comment on #743 contains information about which URL each ribbon button should target: https://github.com/OfficeDev/script-lab/issues/743#issuecomment-362365209.
