### ISSUE TITLE
Assign script to on-click button

### ISSUE THREAD

**Issue by t-1910** [OfficeDev/script-lab#761]
### Description:

In the usual VBA enviroment for MS Excel, a developer can create a service by writing a macro, and then assign the macro to a button. 
In such a way an end-user does not need to enter the "Developer" tab and run the script, but can only click on the button and then have the macro executed. 

Is there a way to assign a script lab code to a button? It would enormously increase the usage of script lab for end-user services.

![Capture](https://user-images.githubusercontent.com/55189249/64694613-4f2e5780-d49a-11e9-9f3c-a2b86235ea53.PNG)

**Comment by Zireael** [comment]
Is it possible to assign function execution when an element in the spreadsheet is clicked, hovered or edited? As @t-1910 said, we need to have seamless integration of user interactions with spreadsheet elements and JavaScript code execution.
Trying to direct users to use ScriptLab pane is not the way to go, as they are not used to something like that.
Users want to click a button/chart/cell in the spreadsheet and see things happen. At the moment the spreadsheet structure and Script Lab pane are totally decoupled from each other in terms of UI.

**Comment by Zireael** [comment]
NB: It would be great if we could create Ribbon tabs/buttons that execute JS code/functions. As for graphics assets for icons, those can be embedded in JS code as SVG or PNG-Base64 for example.

**Comment by wandyezj** [comment]
You can do this with [Office Scripts](https://learn.microsoft.com/en-us/office/dev/scripts/develop/script-buttons)
