### ISSUE TITLE
Loading Loading Loading

### ISSUE THREAD

**Issue by appmakerz00** [OfficeDev/script-lab#766]
### Bug Report

- **Host**: (fill out if relevant. eg: EXCEL)
- **OS**: (Windows 10)
- **Browser**: (Chrome)

#### Actual behavior:

Help / Tutorial and other buttons in Excel just loads and loads  when clicked. The Window that comes up is just white and the Script lab logo is visible with the red loading gif.

#### Steps to Reproduce:

Just using menys 

#### Screenshot:
![freeze](https://user-images.githubusercontent.com/18431338/70617485-fbeeb100-1c10-11ea-8787-fc8a063c934a.png)

**Comment by TCourtneyOwen** [comment]
@appmakerz00 Thanks for reporting this issue.  I am seeing this behavior as well and will open a bug on this and try to get a fix out soon.

-Courtney

**Comment by wandyezj** [comment]
Obsolete.
