### ISSUE TITLE
Script Lab doesn't load Office 2019

### ISSUE THREAD

**Issue by CarlVerret** [OfficeDev/script-lab#771]
Been trying to install on office 2019, now error message, just loading with chasing dots.

Same with Word, Excel.

Script lab tab is inserted and when I click on code or run button, keeps loading.
![Capture](https://user-images.githubusercontent.com/25437410/70950395-6b5c0a80-202e-11ea-8526-f517019f85ee.PNG)

Word MSO 2019 16.0.10730.20102 32 bits version

**Comment by CarlVerret** [comment]
Additionnal info : my windows version is 
Microsoft Windows [version 10.0.14393]

I've search a bit an realized that web add ins are displayed in Internet Explorer ...  Is there a way to change this behavior ?

Thanks

**Comment by warwicklol14** [comment]
I have the same error on Office 2019. I had to install Office 2016 to get it working.

**Comment by ElizabethSamuel-MSFT** [comment]
@CarlVerret @warwicklol14 Script Lab no longer works in perpetual Office 2019 on Windows. For more information, see "Supported clients" in [Explore Office JavaScript API using Script Lab](https://learn.microsoft.com/office/dev/add-ins/overview/explore-with-script-lab#supported-clients).
