### ISSUE TITLE
Event register Or HotKey Event Notification

### ISSUE THREAD

**Issue by Kerryway** [OfficeDev/script-lab#774]
### Description:
Custom  Description:
Valuable Custom Definition Hotey is work，and auto test Script Add-in HotKey  and more

**Comment by wandyezj** [comment]
I recommend creating a full [Add-In](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/develop-overview).

You can create and host your own Add-In on GitHub, for example see the [Build Add-In by wandyezj](https://github.com/wandyezj/build-add-in) you can sideload the [manifest](https://github.com/wandyezj/build-add-in/blob/main/manifests/production.xml).
