### ISSUE TITLE
Error del complemento en excel 2019 32 bit 

### ISSUE THREAD

**Issue by vretamar** [OfficeDev/script-lab#779]
-Este complemento no se puede iniciar.Para ignorar el problema, cierre este dialogo o haga clic en "Reiniciar", para intentarlo nuevamente.
sistema operativo WINDOWS 10 64 bits  , 8gb Ram , office 2019 32 bits

**Comment by vretamar** [comment]
script lab -Este complemento no se puede iniciar.Para ignorar el problema, cierre este diálogo o haga clic en "Reiniciar", para intentarlo nuevamente.
sistema operativo WINDOWS 10 64 bits, 8 gb Ram, oficina 2019 32 bits

**Comment by vretamar** [comment]
![Error_en_Script Lab](https://user-images.githubusercontent.com/29669941/75841819-6eed6b00-5dad-11ea-8b3e-11aeca195e6a.png)

**Comment by nespichan** [comment]
![error](https://user-images.githubusercontent.com/20219491/76826902-9865b800-67eb-11ea-8459-91f7fbd8de9e.png)
No inicia el complemento script lab en office 2016, sistema operativo windows 10, 64 bit de 8 gigas
