### ISSUE TITLE
 Ask the community button, reference docs button and help button not working

### ISSUE THREAD

**Issue by ShrutikaSingh** [OfficeDev/script-lab#780]
### Bug Report

- **Host**: (EXCEL,)
- **OS**: (Mac Os)
- **Browser**: (Chrome)
- **Environment**: (prod)

#### Expected behavior:
Ask the community button, reference docs button and help button should lead us to some page that they are linked to.

#### Actual behavior:
Loading error in Ask the community button, reference docs button and help button. The links or references in these buttons are not working.

#### Failure Logs:
Even after half an hour, the links doesn't load.

**Comment by Zlatkovsky** [comment]
Thanks for reporting!  I have a pull request that will fix it soon (and likely deploying to production tomorrow)

**Comment by Zlatkovsky** [comment]
Fixed.  Should deploy to production tomorrow.
