### ISSUE TITLE
Block IE < 11 or lack of localStorage (Safari Office Online in In-Private mode -- on iOS and maybe Mac)

### ISSUE THREAD

**Issue by Zlatkovsky** [OfficeDev/script-lab#8]

**Comment by Zlatkovsky** [comment]
@WrathOfZombies , what does it take to add this block?

**Comment by Zlatkovsky** [comment]
In the absence of doing something, here is what happens to the editor in IE 9:

![image](https://cloud.githubusercontent.com/assets/2230453/25509302/c177597e-2b6c-11e7-817f-197e3c5fc4f1.png)

**Comment by WrathOfZombies** [comment]
well we need to add modernizr to it inorder to block it. its actually fairly simple. just add a bunch of rules that you want to check against such as flex boxes, localStorage and show an error message if not possible.

**Comment by Zlatkovsky** [comment]
@WrathOfZombies ,  Do you want to submit a pull request, since you know what needs to be added, and where?

**Comment by Zlatkovsky** [comment]
Fixed local storage issue.  And haven't really heard of anyone else running into having a version earlier than Internet explorer 11
