### ISSUE TITLE
No funciona en office 2019

### ISSUE THREAD

**Issue by dalton-ase** [OfficeDev/script-lab#800]
Hola, tengo Office 2019 actualizado 5-04-2020, instale el complemeto desde la tienda de Windows, tengo windows 10, en el momento de ejecutar el boton de "Code" Genera el sigiente error al costado derecho donde se debria ejecutar el codigo.
![error office 2019](https://user-images.githubusercontent.com/19474353/78507166-101c6800-7744-11ea-93de-13c92277222b.PNG)
El mensaje= Error del complemento.
Lo sentimos, no pudimos cargamos el complemento porque internet explorer esta dehabilitada. Para obtener mas informacion, haga clic en "Ver detalles"
Al dar clic en ver detalles me lleva a esta URL.  https://support.office.com/es-es/article/HA102789344?AssetID=HA102789344&ver=16&app=excel.exe&CorrelationId=d07bc252-3863-4962-a25a-8867bf8c11c8.
Gracias por su valiosa ayuda.

![image](https://user-images.githubusercontent.com/19474353/78507285-d861f000-7744-11ea-8a7d-b3c31c63ba61.png)

**Comment by dalton-ase** [comment]
![image](https://user-images.githubusercontent.com/19474353/78507277-cd0ec480-7744-11ea-8312-d34976a96ad4.png)

**Comment by ElizabethSamuel-MSFT** [comment]
@dalton-ase No, Script Lab no longer works in Office 2019 on Windows. For more information, see the "Clientes compatibles" section of the [Explorar la API de JavaScript de Office con el laboratorio de scripts](https://learn.microsoft.com/office/dev/add-ins/overview/explore-with-script-lab#supported-clients).
