### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by Sheccid** [OfficeDev/script-lab#804]
I need help to solve this please, it's in my cell but I don't understand you, I have my cell full of  things like that.

{"mode":"release","deviceId":"0b46bae66f724330a5c265517a5bd44c","pairingDeviceId":"","deviceModel":"SM-G935V","pairingDeviceModel":"","deviceOsVersion":"Android SDK: 26 (8.0.0)","pairingDeviceOsVersion":"","deviceType":"samsung","pairingDeviceType":"","pairingType":"","status":"Transfer Cancelled - Not Started","errorMessage":"","contacts":0,"photos":0,"videos":0,"sms":0,"audio":0,"callLogs":0,"documents":0,"calendars":0,"reminders":0,"wifiSettings":0,"deviceSettings":0,"deviceApps":0,"alarms":0,"wallpapers":0,"voiceRecordings":0,"ringtones":0,"sNotes":0,"transferType":"Receiver","wifiAccessPoint":"","dataTransferred":"0","transferSpeed":"0 Mbps","duration":"0","buildVersion":"3.5.10","description":"MF back button-CT app exit>PhoneSelectionScreen","transferDate":"1587316701045","transferStart":"1587316687177","scanType":"","appType":"MVM","mdn":"2089826422","locationRadioId":"","bluetoothBeaconMajorId":"","bluetoothBeaconMinorId":"","storeId":"","location":"","state":"","region":"","deviceCount":-1,"globalUUID":"cf08449bb1f54a029d5f98cf997d06ae"}{"mode":"release","deviceId":"c8aaa38e2f5d4b10b3d1d4c0d5d17434","pairingDeviceId":"","deviceModel":"SM-G935V","pairingDeviceModel":"","deviceOsVersion":"Android SDK: 26 (8.0.0)","pairingDeviceOsVersion":"","deviceType":"samsung","pairingDeviceType":"","pairingType":"","status":"Transfer Cancelled - Not Started","errorMessage":"","contacts":0,"photos":0,"videos":0,"sms":0,"audio":0,"callLogs":0,"documents":0,"calendars":0,"reminders":0,"wifiSettings":0,"deviceSettings":0,"deviceApps":0,"alarms":0,"wallpapers":0,"voiceRecordings":0,"ringtones":0,"sNotes":0,"transferType":"Receiver","wifiAccessPoint":"","dataTransferred":"0","transferSpeed":"0 Mbps","duration":"0","buildVersion":"3.5.10","description":"MF back button-CT app exit>LandingScreen","transferDate":"1587350973986","transferStart":"1587350968292","scanType":"","appType":"MVM","mdn":"2089826422","locationRadioId":"","bluetoothBeaconMajorId":"","bluetoothBeaconMinorId":"","storeId":"","location":"","state":"","region":"","deviceCount":-1,"globalUUID":"cf08449bb1f54a029d5f98cf997d06ae"}{"mode":"release","deviceId":"156501026f464efbb1425ef5c292fda1","pairingDeviceId":"","deviceModel":"SM-G935V","pairingDeviceModel":"","deviceOsVersion":"Android SDK: 26 (8.0.0)","pairingDeviceOsVersion":"","deviceType":"samsung","pairingDeviceType":"","pairingType":"","status":"Transfer Cancelled - Not Started","errorMessage":"","contacts":0,"photos":0,"videos":0,"sms":0,"audio":0,"callLogs":0,"documents":0,"calendars":0,"reminders":0,"wifiSettings":0,"deviceSettings":0,"deviceApps":0,"alarms":0,"wallpapers":0,"voiceRecordings":0,"ringtones":0,"sNotes":0,"transferType":"Receiver","wifiAccessPoint":"","dataTransferred":"0","transferSpeed":"0 Mbps","duration":"0","buildVersion":"3.5.10","description":"MF back button-CT app exit>LandingScreen","transferDate":"1587351045715","transferStart":"1587351037513","scanType":"","appType":"MVM","mdn":"2089826422","locationRadioId":"","bluetoothBeaconMajorId":"","bluetoothBeaconMinorId":"","storeId":"","location":"","state":"","region":"","deviceCount":-1,"globalUUID":"cf08449bb1f54a029d5f98cf997d06ae"}

**Comment by TCourtneyOwen** [comment]
@Sheccid Can you please include the office-js snippet that you were attempting to run in Script-Lab? That will better help us diagnose what you are seeing.

Thanks,

Courtney

**Comment by Sheccid** [comment]
Could you give me an e-mail to send you information?  the truth I do not understand but I found many things in my cel and although I do not know programming I am sure that someone controls it remotely, I even know that there are hidden accounts I just do not know how to remove everything, I did factory reset and it is not removed  Then I found a file that from what I read protects information from the factory reset, I have many documents, configurations, I just do not know how to reprogram to solve it, if I try to change something in my cell it automatically takes me out and sends it to the home screen, sorry not to explain  more but I don't know much about this and the truth urges me to remove all this, Mi Email is asterflash87@hotmail.com thanks

**Comment by TCourtneyOwen** [comment]
@Sheccid I will respond directly to the email you provided so I can gather more details. It's still very unclear to me how you are using Script-Lab.

- Courtney

**Comment by LiLWest80** [comment]
> I need help to solve this please, it's in my cell but I don't understand you, I have my cell full of things like that.
> 
> {"mode":"release","deviceId":"0b46bae66f724330a5c265517a5bd44c","pairingDeviceId":"","deviceModel":"SM-G935V","pairingDeviceModel":"","deviceOsVersion":"Android SDK: 26 (8.0.0)","pairingDeviceOsVersion":"","deviceType":"samsung","pairingDeviceType":"","pairingType":"","status":"Transfer Cancelled - Not Started","errorMessage":"","contacts":0,"photos":0,"videos":0,"sms":0,"audio":0,"callLogs":0,"documents":0,"calendars":0,"reminders":0,"wifiSettings":0,"deviceSettings":0,"deviceApps":0,"alarms":0,"wallpapers":0,"voiceRecordings":0,"ringtones":0,"sNotes":0,"transferType":"Receiver","wifiAccessPoint":"","dataTransferred":"0","transferSpeed":"0 Mbps","duration":"0","buildVersion":"3.5.10","description":"MF back button-CT app exit>PhoneSelectionScreen","transferDate":"1587316701045","transferStart":"1587316687177","scanType":"","appType":"MVM","mdn":"2089826422","locationRadioId":"","bluetoothBeaconMajorId":"","bluetoothBeaconMinorId":"","storeId":"","location":"","state":"","region":"","deviceCount":-1,"globalUUID":"cf08449bb1f54a029d5f98cf997d06ae"}{"mode":"release","deviceId":"c8aaa38e2f5d4b10b3d1d4c0d5d17434","pairingDeviceId":"","deviceModel":"SM-G935V","pairingDeviceModel":"","deviceOsVersion":"Android SDK: 26 (8.0.0)","pairingDeviceOsVersion":"","deviceType":"samsung","pairingDeviceType":"","pairingType":"","status":"Transfer Cancelled - Not Started","errorMessage":"","contacts":0,"photos":0,"videos":0,"sms":0,"audio":0,"callLogs":0,"documents":0,"calendars":0,"reminders":0,"wifiSettings":0,"deviceSettings":0,"deviceApps":0,"alarms":0,"wallpapers":0,"voiceRecordings":0,"ringtones":0,"sNotes":0,"transferType":"Receiver","wifiAccessPoint":"","dataTransferred":"0","transferSpeed":"0 Mbps","duration":"0","buildVersion":"3.5.10","description":"MF back button-CT app exit>LandingScreen","transferDate":"1587350973986","transferStart":"1587350968292","scanType":"","appType":"MVM","mdn":"2089826422","locationRadioId":"","bluetoothBeaconMajorId":"","bluetoothBeaconMinorId":"","storeId":"","location":"","state":"","region":"","deviceCount":-1,"globalUUID":"cf08449bb1f54a029d5f98cf997d06ae"}{"mode":"release","deviceId":"156501026f464efbb1425ef5c292fda1","pairingDeviceId":"","deviceModel":"SM-G935V","pairingDeviceModel":"","deviceOsVersion":"Android SDK: 26 (8.0.0)","pairingDeviceOsVersion":"","deviceType":"samsung","pairingDeviceType":"","pairingType":"","status":"Transfer Cancelled - Not Started","errorMessage":"","contacts":0,"photos":0,"videos":0,"sms":0,"audio":0,"callLogs":0,"documents":0,"calendars":0,"reminders":0,"wifiSettings":0,"deviceSettings":0,"deviceApps":0,"alarms":0,"wallpapers":0,"voiceRecordings":0,"ringtones":0,"sNotes":0,"transferType":"Receiver","wifiAccessPoint":"","dataTransferred":"0","transferSpeed":"0 Mbps","duration":"0","buildVersion":"3.5.10","description":"MF back button-CT app exit>LandingScreen","transferDate":"1587351045715","transferStart":"1587351037513","scanType":"","appType":"MVM","mdn":"2089826422","locationRadioId":"","bluetoothBeaconMajorId":"","bluetoothBeaconMinorId":"","storeId":"","location":"","state":"","region":"","deviceCount":-1,"globalUUID":"cf08449bb1f54a029d5f98cf997d06ae"}

**Comment by LiLWest80** [comment]
I also have the same exact crap on my phone and I can't get rid of the bug either. I know someone is listening in on my conversation and reading my texts that I make or receive. . I have a bt transmitter that plays music and other media through the car stereo and it's blatantly obvious that someone has accessed my phone for spying on me. So your not crazy and your not just seeing shit ma'am it's real and it's annoying and plz can someone help to get this shit off our devices

**Comment by TCourtneyOwen** [comment]
@LiLWest80 Are you sure this is related to Script Lab? If so, I am going to need details about how you are using Script Lab such as the script you are trying to run.  I can't see how this would be a Script Lab problem specifically, but if you can provide more details that will help to diagnose the issue.

Thanks,

Courtney

**Comment by LouMM** [comment]
Script Lab does now work on Mobile devices, especially Android which is where your logs are coming from at this time.
This repo is only for Office Add-in Script Lab: https://appsource.microsoft.com/en-US/product/office/wa104380862
