### ISSUE TITLE
Disable AppInsights logging temporarily

### ISSUE THREAD

**Issue by saunders77** [OfficeDev/script-lab#815]
AppInsights does not yet support 30-day retention, so instead we will disable temporarily.

Due: Monday, 5/21

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):

## Useful logs

- [ ] Fiddler traces
- [ ] Console errors
- [ ] Screenshots
- [ ] Clip or GIFs

**Comment by Zlatkovsky** [comment]
Fixed with https://github.com/OfficeDev/script-lab/commit/962c5c114645aba60c6c747407bcbb1bf0a4a38e.
Already in master (alpha), merging now into insiders.  Will then push to Prod if all is still well.
