### ISSUE TITLE
Snippet with a name containing only space characters lets the custom function fail

### ISSUE THREAD

**Issue by maninweb** [OfficeDev/script-lab#818]
Hi there,

I am running Script Lab 1.1.0 from the store in Excel Insider (10211.20004) in a Windows 10 VM. I noticed, that a snippet containing only space characters lets the custom function fail.

I followed the steps for adding a custom function. It then looks like the following screenshot and all fine.

![image](https://user-images.githubusercontent.com/13045898/40277745-b636a062-5c24-11e8-8698-7ff135870e0a.png)

Then, created a second snippet, where I changed the custom function name to add20. But in this case I gave the snippet a name including only one or two space characters.

![image](https://user-images.githubusercontent.com/13045898/40277846-5cd65e8e-5c26-11e8-96cb-2f29b6a4c1ff.png)

In the functions pane, the custom function is shown with two dots, as the spaces are trimmed out.

![image](https://user-images.githubusercontent.com/13045898/40277854-9358098a-5c26-11e8-87c1-8d61ad2a4a87.png)

Trying to execute the add20 function then leads to some errors in the console.

![image](https://user-images.githubusercontent.com/13045898/40277872-f4338c8e-5c26-11e8-831a-eccedd343848.png)

Yes, using spaces only for a snippet name does not really make sense, but I think a warning to the user when the snippet name only contains space characters would be useful and therefore would like to suggest a such feature.

Best,
Mourad

**Comment by nico-bellante** [comment]
@Zlatkovsky I think my suggested fix for this one would be to just not allow space only names.. thoughts?

**Comment by Zlatkovsky** [comment]
Works for me!  Do you want to put in that restriction?
Would you put it in at the snippet (editor) level, or flag it as an error for Custom Functions?
I'm fine either way.  I'm just not sure how you would stop at the editor level (other than immediately generating the next "Snippet XYZ" naming -- which would also be OK).

**Comment by Zlatkovsky** [comment]
@nico-bellante , see comment above.

**Comment by nico-bellante** [comment]
This issue seems to be blocked by #413. @Zlatkovsky

**Comment by Zlatkovsky** [comment]
Could we generate a new name as soon as the name becomes empty?
I'm also OK with won't-fixing the bug for now, though.  It seems like a corner-case, so perhaps this can wait until other grander refactoring work.
@nico-bellante, if you want to remove the "cancel" button to solve #413 , go for it.

**Comment by nico-bellante** [comment]
Removed the cancel button in #823
