### ISSUE TITLE
Error: Unable to edit script lab in the browser

### ISSUE THREAD

**Issue by Alex-Mann** [OfficeDev/script-lab#823]
### Bug Report

- **Browser**: Firefox

#### Expected behavior:

Script lab shouldn't error when trying to edit in the browser

#### Actual behavior:

Unable to open script lab in Firefox. Confirmed that there are no issues when using Chrome.

#### Screenshot:

<img width="306" alt="image" src="https://user-images.githubusercontent.com/4520864/87179313-87661880-c2ac-11ea-9276-790b89586e71.png">

**Comment by tobudim** [comment]
I confirm I have the very same situation.
I do not have Chrome, though I use Chromium through Brave.

Browsers:
- Brave v1.16.72 & v1.16.75
- Firefox v82.0.3

OS:
MacOS Catalina 10.15.7
