### ISSUE TITLE
Unable to create new snippet or see Samples

### ISSUE THREAD

**Issue by jainashish26** [OfficeDev/script-lab#824]
## Current Behavior
Below are the images to understand the behaviour of Script-Lab on my machine. It happens across all office products that I tested For eg. Excel, Word or Powerpoint. So, I can't create new snippet and can not see the samples. Interestingly, I can view, edit and run the snippets saved on github gist but I can't create my own or view samples due to this error (see screenshot below)
![1](https://user-images.githubusercontent.com/11323778/40466911-13b7e39c-5f6b-11e8-96ea-5304571a897c.PNG)
![2](https://user-images.githubusercontent.com/11323778/40466915-170037a2-5f6b-11e8-9e5f-edfec2c6c08c.PNG)

## Your Environment
I am using Microsoft Office 365 ProPlus version 1708 (Build 8431.2215) on Windows 10 Operating system (desktop) and default browser is Internet Explorer (11.1029.15063.0). The installation appeared successful. I didn't faced any error during installation. The Script Lab menu is appearing just fine but not working eventually.

**Comment by nico-bellante** [comment]
@Zlatkovsky I am unable to repro this issue. Do you have an older build of office circa Build 8431.2215 to try this on?

**Comment by Zlatkovsky** [comment]
@jainashish26 , the VS debugger is actually not related, it's just trying to access ".js.map" files which are useful for debugging, but that we don't have on the production site.  That's not the problem.

I wonder if there is some issue on your computer / firewall / etc. that is somehow preventing you from accessing GitHub.  Could you try the following URLs and see if they load for you on that same machine?

* https://raw.githubusercontent.com/OfficeDev/office-js-snippets/deploy-prod/playlists/excel.yaml
* https://raw.githubusercontent.com/OfficeDev/office-js-snippets/deploy-prod/samples/excel/01-basics/basic-api-call.yaml

Thanks!

**Comment by jainashish26** [comment]
Unfortunately, the links aren't loading on my machine as something is preventing may be a firewall. I am facing this issue on my office machine so yes, the probability is high for what you say. 

However, I can sign into Github and access other YAML files on gist such as the one on your gist --> [https://gist.github.com/Zlatkovsky/16342cc858fdc4f1c2553566f39ae589](url)

![3](https://user-images.githubusercontent.com/11323778/40517829-bd6ffeb2-5ffa-11e8-884e-a47e950e36e5.PNG)

Also, I can upload files on githubusercontent.com as I just did that by attaching the images on this post. May be I am asking too much from the developers of this revolutionary  Office add-in but can we provide a fall-out link like in the catch condition. So, if a user do not have access to the above links, some other link should be tried.

**Comment by Zlatkovsky** [comment]
The image you uploaded ends up on a different domain.  It's https://user-images.githubusercontent.com, rather than https://raw.githubusercontent.com.  I have no idea why that would make a difference to a firewall, but it is still different domains.

Try accessing any other regular file in github and clicking the "raw" link on it.  E.g.,: https://raw.githubusercontent.com/OfficeDev/script-lab/master/README.md
(got there via clicking "raw" on https://github.com/OfficeDev/script-lab/blob/master/README.md)

You're the first person I've heard of having this issue.

**Comment by Zlatkovsky** [comment]
BTW, as a temporary workaround:  you can browser the samples via https://github.com/OfficeDev/office-js-snippets/tree/master/samples/excel, and then choose one and copy-paste the entire YAML.  Eg.., for the default sample, just paste in the following into the "import" textbox:

```

id: excel-default
name: Blank snippet
description: Create a new snippet from a blank template.
author: OfficeDev
host: EXCEL
api_set:
    ExcelApi: 1.1
script:
    content: |
        $("#run").click(() => tryCatch(run));
        async function run() {
            await Excel.run(async (context) => {
                OfficeHelpers.UI.notify("Your code goes here");
                await context.sync();
            });
        }
        /** Default helper for invoking an action and handling errors. */
        async function tryCatch(callback) {
            try {
                await callback();
            }
            catch (error) {
                OfficeHelpers.UI.notify(error);
                OfficeHelpers.Utilities.log(error);
            }
        }
    language: typescript
template:
    content: |
        <button id="run" class="ms-Button">
            <span class="ms-Button-label">Run</span>
        </button>
    language: html
style:
    content: |
        /* Your style goes here */
    language: css
libraries: |
    https://appsforoffice.microsoft.com/lib/1/hosted/office.js
    https://appsforoffice.microsoft.com/lib/1/hosted/office.d.ts
    office-ui-fabric-js@1.4.0/dist/css/fabric.min.css
    office-ui-fabric-js@1.4.0/dist/css/fabric.components.min.css
    core-js@2.4.1/client/core.min.js
    @types/core-js
    @microsoft/office-js-helpers@0.7.4/dist/office.helpers.min.js
    @microsoft/office-js-helpers@0.7.4/dist/office.helpers.d.ts
    jquery@3.1.1
    @types/jquery
```

**Comment by jainashish26** [comment]
My organisation definitely has a strange firewall which I just came to know as well. I am as surprised as you. 
I can access [https://github.com/OfficeDev/script-lab/blob/master/README.md](url) but when I click Raw, it redirects to [https://raw.githubusercontent.com/OfficeDev/script-lab/master/README.md](url) which I can't access. I will raise this to network team here.

If you wish, feel free to close down the issue as I can access the script-lab using above code and the provided samples link of YAMLs through import.

**Comment by Zlatkovsky** [comment]
Sounds good, glad this got resolved.
If you figure out what exactly the network team did to block or unblock this, I'd be quite curious to learn how this came to be.
Best of luck!
