### ISSUE TITLE
Project Link on GitHub - Quick Fix

### ISSUE THREAD

**Issue by rondemena** [OfficeDev/script-lab#826]
### Bug Report

https://github.com/OfficeDev/script-lab 
GitHub Link is broken - points to https://script-lab.azureedge.net/ for the project website.

I believe the more current link would be https://appsource.microsoft.com/en-us/product/office/WA200001603?tab=Overview

#### Expected behavior:

Link should work.

#### Actual behavior:

Edge, and Chrome both fail to reach the host.  Host can be found with lookup:
Non-authoritative answer:
Name:    cs9.wpc.v0cdn.net
Addresses:  2606:2800:11f:17a5:191a:18d5:537:22f9
          72.21.81.200
Aliases:  script-lab.azureedge.net
          script-lab.ec.azureedge.net

#### Steps to Reproduce:
Click Link on GitHub site pointing to project site link of:
https://script-lab.azureedge.net/

#### Failure Logs:

None

#### Screenshot:

None

**Comment by wandyezj** [comment]
Fixed.
