### ISSUE TITLE
What licence is this issued under?

### ISSUE THREAD

**Issue by Simon-I-Am** [OfficeDev/script-lab#847]
The github tickets mention needing to define it, but don't actually seem to say what it is. I may be missing the obvious, but I've really searched and can't find out.

(I know it uses the Monaco editor - https://github.com/Microsoft/monaco-editor - which is MIT licence, but can't figure for script lab itself)

I'm aware without one it defaults to being copyrighted but I got the impression from various texts - perhaps very wrongly - that the intent was to make this open source

Thanks, Simon

**Comment by wandyezj** [comment]
[MIT License](https://github.com/OfficeDev/script-lab/blob/master/LICENSE)
