### ISSUE TITLE
Protect worksheet will protect non-lock cell for Excel online

### ISSUE THREAD

**Issue by wei6100** [OfficeDev/script-lab#851]
I have issue with protect worksheet in excel online. I will unlock all of the cells in the worksheet, and lock one range, then protect worksheet, after that nothing is editable in the worksheet, even the cells are unlocked. But once I close this file and reopen, everything works as expected, able to edit unlock cells. I don't know this is a bug or just some features not supported in excel online version.

This issue only happens for excel online version, works fine for installed version. I m using latest office.js from official CDN link and can reproduce this issue easily using script lab. 

## Expected Behavior
For excel online, after protect a worksheet, unlock cells should still be editable

## Current Behavior
For excel online, after protect a worksheet, nothing is editable 

## Steps to Reproduce (for bugs)
Running the following code, you can reproduce the issue from script lab
Excel.run(function (ctx) {
  //Worksheet
  var sheet = ctx.workbook.worksheets.getItem("Sheet1");

  //Entire Range
  var entireRange = sheet.getRange();
  entireRange.format.protection.locked = false;  

  //Specific Range
  var range = sheet.getRange("A1:B5");  

  range.format.protection.locked = false;

//Protect Entire sheet
      sheet.protection.protect({
        allowInsertRows: false,
        allowDeleteRows: false
      });

  return ctx.sync();
    
}).catch(errorHandler);

## Your Environment
* Version used: 16.0.10323.10000
* Browser Name and version: Chrome Version 67.0.3396.99

**Comment by Zlatkovsky** [comment]
Sorry, this somehow fell off the radar -- but the Issue doesn't seem to be a Script Lab one, it's an office.js issue.  I assume you've filed a bug on https://github.com/OfficeDev/office-js/issues and/or asked a question on https://stackoverflow.com/tags/office-js?
