### ISSUE TITLE
Didn't download tutorial xlsx

### ISSUE THREAD

**Issue by project-x51** [OfficeDev/script-lab#861]
Hi,

I clicked on the Tutorial button on the script lab ribbon and then the Download link. I get a new window but no download occured. I was able to download the tutorial file in my browser using the link in the window so problem solved but a bug none the less. 

See image link below. Yes its the tutorial sheet in the background as I ran it from inside the sheet after downloading it outside excel.
![image](https://user-images.githubusercontent.com/40679862/106715301-c51ff980-6661-11eb-8fa7-cdfaba8f7b0f.png)

Thanks

Robin

**Comment by wandyezj** [comment]
We have removed this tutorial in the latest version and replaced it with [help](https://learn.microsoft.com/en-us/office/dev/add-ins/overview/explore-with-script-lab) which should be a better experience.
