### ISSUE TITLE
Uninstall ScriptLab?

### ISSUE THREAD

**Issue by rakeshsoni979** [OfficeDev/script-lab#863]
There is not option to uninstall ScriptLab.
It is niether listed in addins nor as a program.
Can you please suggest?

**Comment by junkbond916** [comment]
You have to remove it in add-ins (Insert => Addins => My Addins =>Manage My Addins).  From the Office 365 web page, click "Hide" next to the addin, and the addin will be removed once you refresh per the link below.

https://support.microsoft.com/en-us/office/refresh-the-office-add-ins-list-e612e97c-914b-46a6-9ab7-34789cd76204?omkt=en-us&ui=en-us&rs=en-us&ad=us

**Comment by wandyezj** [comment]
Script Lab is an Office Add-In. Per @junkbond916 you can manage it like any other Office Add-In.

1. In Excel
1. Click Insert
1. Click Addins
1. Click My Addins
1. Hover over the Script Lab
1. Click the `...` 
1. Click Remove

Please let us know if you run into additional issues.
