### ISSUE TITLE
Import a JQuery library while i was customizing a function in excel

### ISSUE THREAD

**Issue by JerryXBear** [OfficeDev/script-lab#864]
### Description:
I try to import the library to grab data from web, but the system said it cannot realize what $ is from JQuery. I think the compiler doesn't identify i have imported JQuery in the function.  After registering and calling the function, it stopped on fetch function and data doesn't display on console. I also tried to grab data calling FETCH and XHR. Neither works. 
### Screenshot(s):
Fetch Case:
![image](https://user-images.githubusercontent.com/49921472/109398243-8d1e7600-78f0-11eb-9e20-abdc69e2984a.png)
![image](https://user-images.githubusercontent.com/49921472/109398254-a6272700-78f0-11eb-9e8f-f3de741efe52.png)

JQuery Case:
![image](https://user-images.githubusercontent.com/49921472/109398306-f4d4c100-78f0-11eb-9c4c-0b4042415ced.png)
![image](https://user-images.githubusercontent.com/49921472/109398333-2b124080-78f1-11eb-821b-11eddffbe362.png)

**Comment by JerryXBear** [comment]
I tried to grab the same data using other tools, All other tools can successfully grab the data using fetch, Jquery.

**Comment by wandyezj** [comment]
Script Lab does not support JQuery with Custom Functions.
