### ISSUE TITLE
Cannot open Script Lab in Excel 2016

### ISSUE THREAD

**Issue by WangZishi** [OfficeDev/script-lab#867]
## Expected Behavior

open the Script Lab

## Current Behavior

![1-excel-2018-09-20-11-51-53](https://user-images.githubusercontent.com/8288105/45795119-942b0e00-bccc-11e8-8c5a-7f2065ee072c.gif)

## Your Environment

* Version used: 
* Browser Name and version: 
* Operating System and version (desktop or mobile): Windows 10 Pro 17763.1

## Useful logs

- [ ] Fiddler traces
- [ ] Console errors
- [ ] Screenshots
- [x] Clip or GIFs

**Comment by Zlatkovsky** [comment]
What about going to the site directly at https://script-lab.azureedge.net?  Could you try that in **Internet Explorer** (which is what the Windows version of Office uses for displaying the taskpane) and see how it renders there?

**Comment by WangZishi** [comment]
@Zlatkovsky 
I can't open the site in the Internet Explorer either.
But Edge is fine.

![default](https://user-images.githubusercontent.com/8288105/46200383-0ee6cf80-c344-11e8-954c-90f9bce4563f.png)

**Comment by Zlatkovsky** [comment]
Ok, thanks for checking.  Is there some sort of firewall or admin policy in effect for you in IE?  Are you able to use other sites in IE?

For now, IE is the rendering engine within Office for desktop, so there's not anything that Script Lab can do about it.  I assume your other add-ins also wouldn't work on desktop, right?

You can, however, use Office Online to unblock yourself.  Or try to identify what causes the underlying IE11 issue.

**Comment by Zlatkovsky** [comment]
Closing as "external" from the perspective of what Script Lab can do about it...
