### ISSUE TITLE
Type error: Cannot find namespace 'monaco'.  TS2503

### ISSUE THREAD

**Issue by g8up** [OfficeDev/script-lab#877]
I launch the lab server in locale , and got an error:
```js
Type error: Cannot find namespace 'monaco'.  TS2503

    40 |   editSettings: (newSettings: string) => void;
    41 |   openSettings: () => void;
  > 42 |   signalEditorLoaded: (editor: monaco.editor.IStandaloneCodeEditor) => void;
       |                                ^
    43 |   applyFormatting: () => void;
    44 | }
    45 |
```
Steps:
- git clone https://github.com/OfficeDev/script-lab
- yarn install
- yarn start

https://github.com/OfficeDev/script-lab/blob/8964c49689d1eed133569960b1ac8eed5dbd5244/packages/editor/src/pages/Editor/components/Main/Editor/index.tsx#L34-L44

**Comment by wandyezj** [comment]
This should work with:

> npm install
> npm run start
