### ISSUE TITLE
Script lab cannot open in local PC

### ISSUE THREAD

**Issue by JerryXBear** [OfficeDev/script-lab#881]
### Bug Report

I loaded a local excel file and used the script lab, however, the lab always on loading screen and never see editor until I uploaded the same file to One cloud and opened it. Script lab can be opened and saw editor. 
By the way, I tried to update Excel and it is the latest version. It still doesn't work.

#### Expected behavior:
Open script in excel while editing a file from local PC.
#### Actual behavior:

Cannot open

#### Steps to Reproduce:

1. step 1
2. step 2
3. etc...

#### Screenshot:
First image: I opened "functions" in script tab

![image](https://user-images.githubusercontent.com/49921472/115287985-bf38a100-a105-11eb-8751-1090c3e890f4.png)

Second Image: Always on loading.

![image](https://user-images.githubusercontent.com/49921472/115288143-f14a0300-a105-11eb-87dc-fccf0afaeaf0.png)

third image: 

![image](https://user-images.githubusercontent.com/49921472/115288212-09218700-a106-11eb-842f-a6c8c4819c36.png)

**Comment by JerryXBear** [comment]
Third issue happened in the same day:


### Bug Report

Excel Script lab.

#### Expected behavior:



#### Actual behavior:

Print the information of each item in dataHierarchies.Class. 

#### Steps to Reproduce:

1. grab worksheet.
2. add pivot table
3. add row into pivot table
4. add dataHierachies into pivot table.
5. run the program

#### Failure Logs:

Excel restarts or shuts down.

#### Screenshot:
## async function run() {
  await Excel.run(async (context) => {
    const sheet = context.workbook.worksheets.getItem("Table");
    const table = sheet.tables.getItem("Table");
    const pivots = sheet.pivotTables;
    const pivot = pivots.add("Temp", table, "Table!J1");

    pivot.rowHierarchies.add(pivot.hierarchies.getItem("Name"));
    pivot.rowHierarchies.add(pivot.hierarchies.getItem("Position"));

    pivot.dataHierarchies.add(pivot.hierarchies.getItem("Age"));

    pivot.dataHierarchies.add(pivot.hierarchies.getItem("Time"));

    pivot.dataHierarchies.add(pivot.hierarchies.getItem("Salary"));

    pivot.dataHierarchies.add(pivot.hierarchies.getItem("Gain"));

    pivot.dataHierarchies.add(pivot.hierarchies.getItem("Tax"));

    pivot.dataHierarchies.add(pivot.hierarchies.getItem("length of career"));

    pivot.dataHierarchies.load("items");

    await context.sync().then(async function () {
      console.log(pivot.dataHierarchies.items[0])
    })
  });
}

##



It is my sample code. You can try this.
![image](https://user-images.githubusercontent.com/49921472/115319780-64b73900-a135-11eb-892f-28af703f3ff3.png)

**Comment by wandyezj** [comment]
Please try on the latest version of Script Lab.
