### ISSUE TITLE
raise xml 5632

### ISSUE THREAD

**Issue by ayasechan** [OfficeDev/script-lab#886]
### Bug Report

- **Host**: excel 2019
- **OS**: Microsoft Windows 10 Enterprise (x64) Build 18363.1082
- **Browser**: no
- **Environment**: prod

#### Expected behavior:

enter the code page

#### Actual behavior:

keep loading

#### Steps to Reproduce:

I can use it normally at first
After I tried to switch the compilation branch, it suddenly became unavailable.
I try to delete `%LOCALAPPDATA%\Microsoft\Office\16.0\Wef\` and `%userprofile%\AppData\Local\Packages\Microsoft.Win32WebViewHost_cw5n1h2txyewy\AC\#!123\INetCache\`
But still can't enter the page and the Win32WebViewHost_cw5n1h2txyewy process takes up a lot of cpu

#### Screenshot:

![屏幕截图 2021-04-30 010830](https://user-images.githubusercontent.com/29854045/116591174-0eed4880-a90e-11eb-990d-e2750c625655.png)
![屏幕截图 2021-04-30 010425](https://user-images.githubusercontent.com/29854045/116591180-101e7580-a90e-11eb-8ddc-6abfa3de5f44.png)
![屏幕截图(9)](https://user-images.githubusercontent.com/29854045/116591182-10b70c00-a90e-11eb-88a0-4ec9bb519676.png)

**Comment by chenxizhang** [comment]
Update to the latest version, and check the network connectivity
