### ISSUE TITLE
How can I switch language to get syntax hightlight experience ?

### ISSUE THREAD

**Issue by g8up** [OfficeDev/script-lab#895]
### Bug Report

- **Host**: Excel
- **OS**: Windows 10
- **Browser**: -
- **Environment**: prod

#### Expected behavior:

- language-switcher shows on status bar to let me set syntax to typescript

#### Actual behavior:

no language-switer on status bar

#### Steps to Reproduce:

1. launch Excel app
2. open script lab editor
3. create a new Snippet to edit

#### Failure Logs:

no

#### Screenshot:
![image](https://user-images.githubusercontent.com/8005686/119236371-9de62d00-bb69-11eb-9aeb-9565e7633662.png)

- `About` info
```
Last Updated: Mon, 29 Mar 2021 22:49:00 GMT
Commit: https://github.com/OfficeDev/script-lab-react/commits/8eb2f132f3092cebcc5e3e4e736dcd104eaf0574
Environment: Production
```

**Comment by chenxizhang** [comment]
I think this issue is related to the network (it just can complete downloading the js trunk). I am also in China, often encountered those kind of issues.

**Comment by wandyezj** [comment]
We now only support TypeScript.
