### ISSUE TITLE
Polish of pop-out editor on Office Online (and understand why some of the changes got lost!)

### ISSUE THREAD

**Issue by nico-bellante** [OfficeDev/script-lab#91]
Allow the editor to be popped out on the WAC to allow for more screen real estate

**Comment by Zlatkovsky** [comment]
Sort of done and checked in now in master -- though I'd like to experiment with it a little bit, to see how well it works in practice (e.g., what should its default size be on the desktop? on the WAC, should it just be a regular tab?; etc.)

**Comment by gergzk** [comment]
@annich-MS , can you handle this one at your convenience?

**Comment by annich-MS** [comment]
@gergzk In progress

**Comment by Zlatkovsky** [comment]
I still need to figure out why the Mac doesn't work, and/or disable it there.

**Comment by Zlatkovsky** [comment]
Hm, I'm really confused.  In addition to the Mac issue, it looks like that in our merging of the precompile branch, some of the changes got lost -- even though they were in master as part of commit f84795e59e67b686dd5b3436718ded66f869ac74

![image](https://user-images.githubusercontent.com/2230453/51222281-df0f0800-18f1-11e9-9edc-af8aa1faca7e.png)

@nico-bellante , let's take a look at this together tomorrow.  I want to fix this issue, but I also want to make sure there weren't some other things that got accidentally missed.  We might want to spend an hour or so to dig deeper, and to validate that other code made it in successfully...

**Comment by nico-bellante** [comment]
My guess is this happened since I had already branched off for the remove precompile stuff before the pop out editor code got into master. My branch said delete the file, his branch said add these things to the file, and git chose my changes. I'd say anything between when I made the remove-precompile branch and when it got merged in could possibly be missing.

**Comment by Zlatkovsky** [comment]
For the lost code, re-porting it back in PR https://github.com/OfficeDev/script-lab/pull/575
