### ISSUE TITLE
Shift key not usable to expand code selection in code panel

### ISSUE THREAD

**Issue by McTrk** [OfficeDev/script-lab#918]
Pressing shift while moving cursor expands current selection of cells on Excel worksheet instead of expanding the selected code lines in code window. 
Current workaround is to use mouse, or key chord [Ctrl + Shift + {Arrow Key}] to expand code selection.

**Comment by chenxizhang** [comment]
I can use the Shift key to do this if the cursor is in the code panel. 

Not sure why you faced this issue, might be related to conflict of the shortcut keys settings.
