### ISSUE TITLE
I can't download a MS Word example from 

### ISSUE THREAD

**Issue by gthaker** [OfficeDev/script-lab#931]
### Description:

I can't download the sample "open in word" link. My MS Word applications starts, but it then says "requested information can't be downloaded." 

Is there a place where I can download a sample .doc file, click "enable editing" and "Trust the add-in" and get started with script-lab for windows 10? (I have Microsoft 365 installed.)  When using script-lab I don't have to bother downloading and setting up node, npm or any other software environment, that is a huge plus as I am trying to share with others using script-lab.

### Screenshot(s):
![image](https://user-images.githubusercontent.com/12518676/143470466-8766e305-f48b-4f6e-98e2-27ddf269f001.png)

**Comment by gthaker** [comment]
I meant if they have ScriptLab installed then sharing such a document should 'carry' my add-in with it. 

Since my post I have learned a bit more and I am  sharing my add in (still for testing) with a manifest.xml and sharing the code for the Add-in from a remote web server. this works, but I had though developing and sharing would be easier by Scriptlab, but it is not clear if Scriptlab can support complex Add-in with many HTML, CSS and JS files over many folders.

**Comment by wandyezj** [comment]
This is a cool idea.
However, I this scenario is beyond the design goals of Script Lab which is to provide an easy way for people to try out office.js.
