### ISSUE TITLE
How to use react in script-lab

### ISSUE THREAD

**Issue by Edward-Zhou** [OfficeDev/script-lab#950]
I want to confirm whether we can use react in script-lab like

```
class HelloMessage extends React.Component {
  render() {
    return <div>Hello {this.props.name}</div>;
  }
}

root.render(<HelloMessage name="Taylor" />);
```

**Comment by chenxizhang** [comment]
Maybe...... but it's NOT necessary at all.
The key point of Script lab is "Script", not the UI, so it is better to focus more on the script part.

If you want to have some good functions in the UI, you can use jQuery instead. it's supported by default.

**Comment by wandyezj** [comment]
If you need to use react I recommend creating a full [Add-In](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/develop-overview)

You can create and host your own Add-In on GitHub, for example see the [Build Add-In](https://github.com/wandyezj/website-react-extension) you can sideload the [manifest](https://github.com/wandyezj/website-react-extension/blob/main/manifests/production.xml)
