### ISSUE TITLE
Install ScriptLab via winget

### ISSUE THREAD

**Issue by Pher0ah** [OfficeDev/script-lab#958]
### Description:
 For IT Admins; it would be great to be able to install ScriptLab via scripting (command line); to allow for selective install based on user roles, etc.

**Comment by chenxizhang** [comment]
@Pher0ah  You can do this though the admin center, https://docs.microsoft.com/en-us/microsoft-365/admin/manage/manage-addins-in-the-admin-center?view=o365-worldwide
