### ISSUE TITLE
console.clear/count is ignored

### ISSUE THREAD

**Issue by sdudnic** [OfficeDev/script-lab#966]
### Bug Report

- **Host**: EXCEL
- **OS**: Windows 10
- **Browser**: -
- **Environment**: prod

#### Expected behavior:

* `console.clear()` command should clear the console (ScriptLab console under "Last updated...")
* `console.count()` command should display the log counter 

#### Actual behavior:

* `console.clear()` command is ignored
* `console.count()` command is ignored

#### Steps to Reproduce:

1. Open any excel project and add to you script: `console.log("test"); console.clear();console.count(); console.log("test2")`

**Comment by wandyezj** [comment]
Thank you @sdudnic for the suggestion. 

Script Lab is intended as a playground to try out office.js. 

If you need more advanced functionality, I recommend creating a full [Add-In](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/develop-overview).

You can create and host your own Add-In on GitHub, for example see the [Build Add-In](https://github.com/wandyezj/website-react-extension) you can sideload the [manifest](https://github.com/wandyezj/website-react-extension/blob/main/manifests/production.xml).
