### ISSUE TITLE
The keyboard shortcut "F2" is not unique in contextual menu

### ISSUE THREAD

**Issue by sdudnic** [OfficeDev/script-lab#969]
### Bug Report

- **Host**: EXCEL
- **OS**: Windows 10
- **Browser**: -
- **Environment**: prod

#### Expected behavior:

The pressing of F2 in the code editor, should normally rename the variable. 

#### Actual behavior:

Actually it triggers the suggestion. But that is the `Ctrl+;` shortcut in Visual Studio!

#### Steps to Reproduce:

1. Open Code editor in Excel, and position on one variable.
2. right click on it
3. observe the F2 duplicate keyboard shortcut

#### Screenshot:

![image](https://user-images.githubusercontent.com/35489219/196716987-5268963d-48fd-42ed-9b2c-debc4e073809.png)

**Comment by wandyezj** [comment]
This is certainly questionable behavior. Script Lab manually overwrites F2 in monaco.

It is certainly annoying that a key feature is being overwritten.

**Comment by sdudnic-ingerop** [comment]
F2 in Windows is a classic shortcut to rename things. I don't know what "trigger suggestion" does and not really care, but is a pity the F2 shortcut can't be used because of this "suggestion". I'd remove this option at all.

**Comment by wandyezj** [comment]
@sdudnic-ingerop Thank you for opening this issue. 👍

Fixed in latest version `Fix rename with F2` released today.
