### ISSUE TITLE
Could not load Script Lab from China location without proxy

### ISSUE THREAD

**Issue by Edward-Zhou** [OfficeDev/script-lab#971]
I am trying to load Script Lab from Office Addins Store, and the script lab load failed.

It seems the Script Lab site page is blocked by China.

Is there any way to access Script Lab from China location?

**Comment by wandyezj** [comment]
We have recently moved to a new CDN, hopefully this one is not blocked, please let me know if this has solved the issue.

**Comment by 0x1orz** [comment]
This issue still  is my  trouble, even with a network proxy. 
![屏幕截图 2024-09-07 205408](https://github.com/user-attachments/assets/c9dd276a-3304-4737-b515-41a5215d7a4b)
