### ISSUE TITLE
Script Lab no longer supports ...

### ISSUE THREAD

**Issue by topl0305** [OfficeDev/script-lab#985]
### Bug Report

- **Host**: EXCEL 2013
- **OS**: Windows 10
- **Browser**: Edge, Chrome
- **Environment**: must be prod (company PC)

#### Expected behavior:

After inserting add-in to have the ability to write js.

#### Actual behavior:

Get a screen with message - "Script Lab no longer supports the Internet Explorer 11 browser or embedded browser control. Please upgrade to a [supported version](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins) of Microsoft 365 or open Office on the web in a [supported browser](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins)."

Link sends to download Edge browser, but I already have it!

#### Steps to Reproduce:

1. Go to Insert
2. Shop
3. Get Script Lab and try to run

No Office 365 account.

#### Failure Logs:

Not sure where to search

#### Screenshot:

<img width="1628" alt="script-lab" src="https://user-images.githubusercontent.com/58388770/218448402-79f427a9-85c7-411c-b0e6-b3bec5f59dc6.png">

**Comment by ElizabethSamuel-MSFT** [comment]
@topl0305 If you're still facing this issue, perhaps the following can help provide details to unblock you: "Supported clients" section of [Explore Office JavaScript API using Script Lab](https://learn.microsoft.com/office/dev/add-ins/overview/explore-with-script-lab#supported-clients)]

Also, can you open Excel in Microsoft Edge or another browser that supports Office Add-ins? You should be able to use Script Lab there as well.

**Comment by wandyezj** [comment]
Closing old issue.
