### ISSUE TITLE
how to run script-lab on localhost

### ISSUE THREAD

**Issue by charlessoft** [OfficeDev/script-lab#988]
step1:
[git clone ](https://github.com/OfficeDev/script-lab.git)

step 2:
```
yarn install
yarn run start
```
step 3:
open the url https://localhost:3000, error occured
![image](https://user-images.githubusercontent.com/1197035/218719827-f7454278-8b89-4328-a093-38bfe0772bd6.png)

**Comment by wandyezj** [comment]
> git clone
> npm install
> npm run start
