### ISSUE TITLE
Cannot import scripts from gist on Chrome: You must provide valid gist YAML or a valid gist url.

### ISSUE THREAD

**Issue by IvanaGyro** [OfficeDev/script-lab#993]
I cannot import scripts from gist on Chrome. After inserting the link, the first click of the button will not respond and the second click will result in an error message: "You must provide valid gist YAML or a valid gist url."

### Bug Report

- **Host**: PowerPoint, Word on the web
- **OS**: Windows, MacOS
- **Browser**: Chrome
- **Environment**: prod

#### Expected behavior:

Successfully import the script and jump to the coding tab.

#### Actual behavior:

After inserting the link, the first click of the button will not respond and the second click will result in an error message: "You must provide valid gist YAML or a valid gist url."

#### Steps to Reproduce:

1. Copy & paste https://gist.github.com/IvanaGyro/6e4eea78d24760211d127e9c67b2f335 to the import tab of Script Lab for PowerPoint.
2. Click import -> not respond
3. Click import again -> error message: "You must provide valid gist YAML or a valid gist url."

#### Failure Logs:

No error message in the console panel.

#### Screenshot:

<img width="411" alt="image" src="https://user-images.githubusercontent.com/11438642/222898332-538e07d1-291a-4b26-8f4c-2f64d9dda680.png">

#### More Information

This issue doesn't happen on FireFox.

**Comment by IvanaGyro** [comment]
Here is an workaround.

You can copy paste the raw YAML into the text box. By this method, you will be able to import the script. However, I will not be able to update the script on the gist.

**Comment by wandyezj** [comment]
Fixed in the latest version of Script Lab.
